#!/bin/bash -e

. /usr/share/debconf/confmodule

export PATH=$PATH:/sbin:/usr/sbin:/bin:/usr/bin

# This command can be used as pipe to syslog. With "-s" it also logs to stderr.
ERR_LOGGER="logger -p daemon.err -t hugnetlib -i -s"

db_input critical hugnetlib/mysql_db || true
db_go

db_input critical hugnetlib/mysql_root_user || true
db_go

db_input critical hugnetlib/mysql_root_pw || true
db_go


exit 0
