#!/bin/sh

. /usr/share/debconf/confmodule

export PATH=$PATH:/sbin:/usr/sbin:/bin:/usr/bin

db_get hugnetlib/mysql_db
MYSQLDB=${RET}
db_get hugnetlib/mysql_root_user
MYSQLUSER=${RET}
db_get hugnetlib/mysql_root_pw
MYSQLPW=${RET}

mysql -f -u ${MYSQLUSER} -p"${MYSQLPW}" --database=${MYSQLDB} < /usr/share/HUGnetLib/sql/mysql/0.10.4/fixoutputprocess.sql > /dev/null 2>&1 || true
mysql -f -u ${MYSQLUSER} -p"${MYSQLPW}" --database=${MYSQLDB} < /usr/share/HUGnetLib/sql/mysql/0.10.4/double.sql > /dev/null 2>&1 || true
mysql -f -u ${MYSQLUSER} -p"${MYSQLPW}" --database=${MYSQLDB} < /usr/share/HUGnetLib/sql/mysql/0.11.0/devices.sql > /dev/null 2>&1 || true
mysql -f -u ${MYSQLUSER} -p"${MYSQLPW}" --database=${MYSQLDB} < /usr/share/HUGnetLib/sql/mysql/0.12.0/iopdefaultid.sql > /dev/null 2>&1 || true

exit $?
