ALTER TABLE `e00393700_history` ADD `Data13` FLOAT NULL DEFAULT NULL ,
    ADD `Data14` FLOAT NULL DEFAULT NULL ,
    ADD `Data15` FLOAT NULL DEFAULT NULL ,
    ADD `Data16` FLOAT NULL DEFAULT NULL ,
    ADD `Data17` FLOAT NULL DEFAULT NULL ,
    ADD `Data18` FLOAT NULL DEFAULT NULL ,
    ADD `Data19` FLOAT NULL DEFAULT NULL ;
ALTER TABLE `e00393700_average` ADD `Data13` FLOAT NULL DEFAULT NULL ,
    ADD `Data14` FLOAT NULL DEFAULT NULL ,
    ADD `Data15` FLOAT NULL DEFAULT NULL ,
    ADD `Data16` FLOAT NULL DEFAULT NULL ,
    ADD `Data17` FLOAT NULL DEFAULT NULL ,
    ADD `Data18` FLOAT NULL DEFAULT NULL ,
    ADD `Data19` FLOAT NULL DEFAULT NULL ;

