ALTER TABLE `e00393700_history` ADD `Data13` DOUBLE NULL DEFAULT NULL ,
    ADD `Data14` DOUBLE NULL DEFAULT NULL ,
    ADD `Data15` DOUBLE NULL DEFAULT NULL ,
    ADD `Data16` DOUBLE NULL DEFAULT NULL ,
    ADD `Data17` DOUBLE NULL DEFAULT NULL ,
    ADD `Data18` DOUBLE NULL DEFAULT NULL ,
    ADD `Data19` DOUBLE NULL DEFAULT NULL ;
ALTER TABLE `e00393700_average` ADD `Data13` DOUBLE NULL DEFAULT NULL ,
    ADD `Data14` DOUBLE NULL DEFAULT NULL ,
    ADD `Data15` DOUBLE NULL DEFAULT NULL ,
    ADD `Data16` DOUBLE NULL DEFAULT NULL ,
    ADD `Data17` DOUBLE NULL DEFAULT NULL ,
    ADD `Data18` DOUBLE NULL DEFAULT NULL ,
    ADD `Data19` DOUBLE NULL DEFAULT NULL ;

