<?php
/**
 * Tests the filter class
 *
 * PHP Version 5
 *
 * <pre>
 * HUGnetLib is a library of HUGnet code
 * Copyright (C) 2012 Hunt Utilities Group, LLC
 * Copyright (C) 2009 Scott Price
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 * </pre>
 *
 * @category   Libraries
 * @package    HUGnetLibTest
 * @subpackage SuiteContainers
 * @author     Scott Price <prices@hugllc.com>
 * @copyright  2012 Hunt Utilities Group, LLC
 * @copyright  2009 Scott Price
 * @license    http://opensource.org/licenses/gpl-license.php GNU Public License
 * @link       https://dev.hugllc.com/index.php/Project:HUGnetLib
 *
 */

/** This is a required class */
require_once CODE_BASE.'containers/PacketContainer.php';
/** This is a required class */
require_once CODE_BASE.'tables/PacketSocketTable.php';
/** This is a required class */
require_once TEST_CONFIG_BASE.'stubs/DummySocketContainer.php';

/**
 * Test class for filter.
 * Generated by PHPUnit_Util_Skeleton on 2007-10-30 at 08:44:56.
 *
 * @category   Libraries
 * @package    HUGnetLibTest
 * @subpackage SuiteContainers
 * @author     Scott Price <prices@hugllc.com>
 * @copyright  2012 Hunt Utilities Group, LLC
 * @copyright  2009 Scott Price
 * @license    http://opensource.org/licenses/gpl-license.php GNU Public License
 * @version    Release: 0.9.7
 * @link       https://dev.hugllc.com/index.php/Project:HUGnetLib
 */
class PacketContainerTest extends PHPUnit_Framework_TestCase
{

    /**
    * Sets up the fixture, for example, open a network connection.
    * This method is called before a test is executed.
    *
    * @return null
    *
    * @access protected
    */
    protected function setUp()
    {
        $config = array(
            "sockets" => array(
                array(
                    "dummy" => true,
                ),
                array(
                    "dummy" => true,
                    "group" => "other",
                ),
            ),
        );
        $this->config = &ConfigContainer::singleton();
        $this->config->forceConfig($config);
        $this->socket["default"] = &$this->config->sockets->getSocket("default");
        $this->socket["other"] = &$this->config->sockets->getSocket("other");
        $this->o = new PacketContainer();
    }

    /**
    * Tears down the fixture, for example, close a network connection.
    * This method is called after a test is executed.
    *
    * @return null
    *
    * @access protected
    */
    protected function tearDown()
    {
        $this->o = null;
        $this->config = null;
        $this->socket = null;
    }
    /**
    * data provider for testDeviceID
    *
    * @return array
    */
    public static function dataConstructor()
    {
        return array(
            array(
                "5A5A5A55000ABC0000200401020304C3",
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => "01020304",
                    "Type" => "SENSORREAD",
                    "Reply" => null,
                    "Checksum" => "C3",
                    "Timeout"  => 5,
                    "Retries"  => 3,
                    "GetReply" => true,
                    "group"    => "default",
                ),
                true,
            ),
            array(
                "This is not a packet",
                array(
                    "To" => "000000",
                    "From" => "000000",
                    "Command" => "00",
                    "Length"  => 0,
                    "Data" => "",
                    "Type" => "UNKNOWN",
                    "Reply" => null,
                    "Checksum" => "00",
                    "Timeout"  => 5,
                    "Retries"  => 3,
                    "GetReply" => true,
                    "group"    => "default",
                ),
                true,
            ),
            array(
                "",
                array(
                    "To" => "000000",
                    "From" => "000000",
                    "Command" => "00",
                    "Length"  => 0,
                    "Data" => "",
                    "Type" => "UNKNOWN",
                    "Reply" => null,
                    "Checksum" => "00",
                    "Timeout"  => 5,
                    "Retries"  => 3,
                    "GetReply" => true,
                    "group"    => "default",
                ),
                true,
            ),
            array(
                array(),
                array(
                    "To" => "000000",
                    "From" => "000000",
                    "Command" => "00",
                    "Length"  => 0,
                    "Data" => "",
                    "Type" => "UNKNOWN",
                    "Reply" => null,
                    "Checksum" => "00",
                    "Timeout"  => 5,
                    "Retries"  => 3,
                    "GetReply" => true,
                    "group"    => "default",
                ),
                true,
            ),
            array(
                new PacketSocketTable(),
                array(
                    "To" => "000000",
                    "From" => "000000",
                    "Command" => "00",
                    "Length"  => 0,
                    "Data" => "",
                    "Type" => "UNKNOWN",
                    "Reply" => null,
                    "Checksum" => "00",
                    "Timeout"  => 5,
                    "Retries"  => 3,
                    "GetReply" => true,
                    "group"    => "default",
                ),
                true,
            ),
            array(
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => "01020304",
                    "Timeout"  => 3,
                    "Retries"  => 5,
                    "GetReply" => false,
                    "group"    => "myGroup",
                ),
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => "01020304",
                    "Type" => "SENSORREAD",
                    "Reply" => null,
                    "Checksum" => "C3",
                    "Timeout"  => 3,
                    "Retries"  => 5,
                    "GetReply" => false,
                    "group"    => "myGroup",
                ),
                false,
            ),
            array(
                array(
                    "To" => 621,
                    "From" => 248,
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => "01020304",
                    "Timeout"  => 3,
                    "Retries"  => 5,
                    "GetReply" => false,
                    "group"    => "myGroup",
                ),
                array(
                    "To" => "00026D",
                    "From" => "0000F8",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => "01020304",
                    "Type" => "SENSORREAD",
                    "Reply" => null,
                    "Checksum" => "C2",
                    "Timeout"  => 3,
                    "Retries"  => 5,
                    "GetReply" => false,
                    "group"    => "myGroup",
                ),
                false,
            ),
            array(
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => array(1,2,3,4),
                    "Timeout"  => 3,
                    "Retries"  => 5,
                    "GetReply" => false,
                ),
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => "01020304",
                    "Type" => "SENSORREAD",
                    "Reply" => null,
                    "Checksum" => "C3",
                    "Timeout"  => 3,
                    "Retries"  => 5,
                    "GetReply" => false,
                    "group"    => "default",
                ),
                true,
            ),
            array(
                new PacketSocketTable(
                    array(
                        "group" => "default",
                        "id" => null,
                        "Date" => "2003-03-24 02:21:24",
                        "Command" => "5C",
                        "PacketFrom" => "654321",
                        "PacketTo" => "123456",
                        "RawData" => "0102",
                        "Type" => "CONFIG",
                        "ReplyTime" => 0.0,
                        "Checked" => 0,
                    )
                ),
                array(
                    "To" => "123456",
                    "From" => "654321",
                    "Command" => "5C",
                    "Length"  => 2,
                    "Data" => "0102",
                    "Type" => "CONFIG",
                    "Reply" => null,
                    "Checksum" => "2A",
                    "Timeout"  => 5,
                    "Retries"  => 3,
                    "GetReply" => true,
                    "group"    => "default",
                ),
                true,
            ),
        );
    }
    /**
    * test the set routine when an extra class exists
    *
    * @param array $preload The value to preload
    * @param array $expect  The expected return
    * @param array $sock    If we expect a socket connection
    *
    * @return null
    *
    * @dataProvider dataConstructor
    */
    public function testConstructor($preload, $expect, $sock)
    {
        $obj = new PacketContainer($preload);
        $ret = $this->readAttribute($obj, "data");
        $this->checkDateTime($ret, false);
        // Check to make sure the data var is set correctly
        //$this->assertEquals($expect, $ret);
        // Check the configuration is set correctly
        foreach ($expect as $key => $value) {
            $this->assertSame($value, $obj->$key, "Bad Value in key $key");
        }

        $config = $this->readAttribute($obj, "myConfig");
        $this->assertSame("ConfigContainer", get_class($config));
        // Check the socket is set correctly
        $socket = $this->readAttribute($obj, "mySocket");
        $this->assertSame($sock, is_object($socket));
    }
    /**
    * data provider for testDeviceID
    *
    * @return array
    */
    public static function dataToArray()
    {
        return array(
            array( // #0
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => "01020304",
                    "Type" => "UNKNOWN",
                    "Reply" => null,
                    "Checksum" => "C3",
                    "CalcChecksum" => "C3",
                ),
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => array(1,2,3,4),
                    "RawData" => "01020304",
                    "Type" => "SENSORREAD",
                    "Reply" => null,
                    "Checksum" => "C3",
                    "CalcChecksum" => "C3",
                ),
            ),
            array( // #1
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "EF",
                    "Length"  => 4,
                    "Data" => "01020304",
                    "Type" => "UNKNOWN",
                    "Reply" => null,
                    "Checksum" => "C3",
                    "CalcChecksum" => "C3",
                ),
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "EF",
                    "Length"  => 4,
                    "Data" => array(1,2,3,4),
                    "RawData" => "01020304",
                    "Type" => "UNKNOWN",
                    "Reply" => null,
                    "Checksum" => "79",
                    "CalcChecksum" => "79",
                ),
            ),
            array( // #2
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => "01020304",
                    "Type" => "UNKNOWN",
                    "Reply" => new PacketContainer("5A5A5A5CABCDEF00002000F5"),
                    "Checksum" => "C3",
                    "CalcChecksum" => "C3",
                ),
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => array(1,2,3,4),
                    "RawData" => "01020304",
                    "Type" => "SENSORREAD",
                    "Reply" => array(
                        "To" => "ABCDEF",
                        "From" => "000020",
                        "Command" => "5C",
                        "Length"  => 0,
                        "Data" => array(),
                        "RawData" => "",
                        "Type" => "CONFIG",
                        "Reply" => null,
                        "Checksum" => "F5",
                        "CalcChecksum" => "F5",
                    ),
                    "Checksum" => "C3",
                    "CalcChecksum" => "C3",
                ),
            ),

        );
    }

    /**
    * test the set routine when an extra class exists
    *
    * @param array $preload The value to preload
    * @param array $expect  The expected return
    *
    * @return null
    *
    * @dataProvider dataToArray
    */
    public function testToArray($preload, $expect)
    {
        $this->o->fromArray($preload);
        $ret = $this->o->toArray();
        $this->checkDateTime($ret, false);
        $this->assertEquals($expect, $ret);
    }
    /**
    * data provider for testDeviceID
    *
    * @return array
    */
    public static function dataFromArray()
    {
        return array(
            array(
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => array(1,2,3,4),
                    "RawData" => "01020304",
                    "Type" => "SENSORREAD",
                    "Reply" => array(
                        "To" => "ABCDEF",
                        "From" => "000020",
                        "Command" => "5C",
                        "Length"  => 0,
                        "Data" => array(),
                        "RawData" => "",
                        "Type" => "CONFIG",
                        "Reply" => null,
                        "Checksum" => "F5",
                        "CalcChecksum" => "F5",
                    ),
                    "Checksum" => "C3",
                    "CalcChecksum" => "C3",
                ),
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => array(1,2,3,4),
                    "RawData" => "01020304",
                    "Type" => "SENSORREAD",
                    "Reply" => array(
                        "To" => "ABCDEF",
                        "From" => "000020",
                        "Command" => "5C",
                        "Length"  => 0,
                        "Data" => array(),
                        "RawData" => "",
                        "Type" => "CONFIG",
                        "Reply" => null,
                        "Checksum" => "F5",
                        "CalcChecksum" => "F5",
                    ),
                    "Checksum" => "C3",
                    "CalcChecksum" => "C3",
                ),
            ),
        );
    }

    /**
    * test the set routine when an extra class exists
    *
    * @param array $preload The value to preload
    * @param array $expect  The expected return
    *
    * @return null
    *
    * @dataProvider dataFromArray
    */
    public function testFromArray($preload, $expect)
    {
        $this->o->fromArray($preload);
        $ret = $this->o->toArray();
        $this->checkDateTime($ret, false);
        $this->assertSame($expect, $ret);
    }
    /**
    * data provider for testDeviceID
    *
    * @return array
    */
    public static function dataFromPktString()
    {
        return array(
            array(
                "5A5A5A55000ABC0000200401020304C3",
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => "01020304",
                    "Type" => "SENSORREAD",
                    "Reply" => null,
                    "Checksum" => "C3",
                    "Timeout"  => 5,
                    "Retries"  => 3,
                    "GetReply" => true,
                    "group"    => "default",
                ),
            ),
            array(
                "5A5A5A5C000ABC00002000CA",
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "5C",
                    "Length"  => 0,
                    "Data" => "",
                    "Type" => "CONFIG",
                    "Reply" => null,
                    "Checksum" => "CA",
                    "Timeout"  => 5,
                    "Retries"  => 3,
                    "GetReply" => true,
                    "group"    => "default",
                ),
            ),
            array(
                "5A5A5A5CABCDEF00002000F5",
                array(
                    "To" => "ABCDEF",
                    "From" => "000020",
                    "Command" => "5C",
                    "Length"  => 0,
                    "Data" => "",
                    "Type" => "CONFIG",
                    "Reply" => null,
                    "Checksum" => "F5",
                    "Timeout"  => 5,
                    "Retries"  => 3,
                    "GetReply" => true,
                    "group"    => "default",
                ),
            ),
            array(
                "This is not a packet",
                array(
                    "To" => "000000",
                    "From" => "000000",
                    "Command" => "00",
                    "Length"  => 0,
                    "Data" => "",
                    "Type" => "UNKNOWN",
                    "Reply" => null,
                    "Checksum" => "00",
                    "Timeout"  => 5,
                    "Retries"  => 3,
                    "GetReply" => true,
                    "group"    => "default",
                ),
            ),
        );
    }
    /**
    * test the set routine when an extra class exists
    *
    * @param array $preload The value to preload
    * @param array $expect  The expected return
    *
    * @return null
    *
    * @dataProvider dataFromPktString
    */
    public function testFromPktString($preload, $expect)
    {
        $this->o->fromPktString($preload);
        $ret = $this->readAttribute($this->o, "data");
        $this->checkDateTime($ret, false);
        foreach ($expect as $key => $value) {
            $this->assertSame($value, $this->o->$key, "Bad Value in key $key");
        }
    }
    /**
    * data provider for testDeviceID
    *
    * @return array
    */
    public static function dataRecv()
    {
        return array(
            // packet timeout
            array(
                "5A5A5A55000ABC0000200401020304C3",
                "5A5A5A01000020000ABC0401020304",
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => array(1,2,3,4),
                    "RawData" => "01020304",
                    "Type" => "SENSORREAD",
                    "Reply" => null,
                    "Checksum" => "C3",
                    "CalcChecksum" => "C3",
                ),
                false,
            ),
            // bad checksum
            array(
                "5A5A5A55000ABC0000200401020304C3",
                "5A5A5A01000020000ABC040102030412",
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => array(1,2,3,4),
                    "RawData" => "01020304",
                    "Type" => "SENSORREAD",
                    "Reply" => null,
                    "Checksum" => "C3",
                    "CalcChecksum" => "C3",
                ),
                false,
            ),
            // Good Reply
            array(
                "5A5A5A55000ABC0000200401020304C3",
                "0ABC0000200401020304C3A134389105239258"
                ."5A5A5A01000020000ABC040102030497",
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => array(1,2,3,4),
                    "RawData" => "01020304",
                    "Type" => "SENSORREAD",
                    "Reply" => array(
                        "To" => "000020",
                        "From" => "000ABC",
                        "Command" => "01",
                        "Length"  => 4,
                        "Data" => array(1,2,3,4),
                        "RawData" => "01020304",
                        "Type" => "REPLY",
                        "Reply" => null,
                        "Checksum" => "97",
                        "CalcChecksum" => "97",
                    ),
                    "Checksum" => "C3",
                    "CalcChecksum" => "C3",
                ),
                true,
            ),
            // No reply expected
            array(
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => "01020304",
                ),
                "5A5A5A5E000000000ABC0401020304E8",
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => array(1,2,3,4),
                    "RawData" => "01020304",
                    "Type" => "SENSORREAD",
                    "Reply" => null,
                    "Checksum" => "C3",
                    "CalcChecksum" => "C3",
                ),
                false,
            ),
            // No reply expected
            array(
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => "01020304",
                ),
                null,
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => array(1,2,3,4),
                    "RawData" => "01020304",
                    "Type" => "SENSORREAD",
                    "Reply" => null,
                    "Checksum" => "C3",
                    "CalcChecksum" => "C3",
                ),
                false,
            ),
            // Bad Checksum
            array(
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => "01020304",
                ),
                "5A5A5A5E000000000ABC0401020304E9",
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => array(1,2,3,4),
                    "RawData" => "01020304",
                    "Type" => "SENSORREAD",
                    "Reply" => null,
                    "Checksum" => "C3",
                    "CalcChecksum" => "C3",
                ),
                false,
            ),
            // No reply expected
            array(
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => "01020304",
                ),
                "5A5A5A010000200ABC00040102030497",
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => array(1,2,3,4),
                    "RawData" => "01020304",
                    "Type" => "SENSORREAD",
                    "Reply" => null,
                    "Checksum" => "C3",
                    "CalcChecksum" => "C3",
                ),
                false,
            ),
            // No reply expected
            array(
                array(
                    "GetReply" => false,
                ),
                "5A5A5A010000200ABC00040102030497",
                array(
                    "To" => "000020",
                    "From" => "0ABC00",
                    "Command" => "01",
                    "Length"  => 4,
                    "Data" => array(1,2,3,4),
                    "RawData" => "01020304",
                    "Type" => "REPLY",
                    "Reply" => null,
                    "Checksum" => "97",
                    "CalcChecksum" => "97",
                ),
                true,
            ),
            // Only Part of a packet
            array(
                array(
                    "GetReply" => false,
                ),
                "5A5A5A0100002",
                array(
                    "To" => "000000",
                    "From" => "000000",
                    "Command" => "00",
                    "Length"  => 0,
                    "Data" => array(),
                    "RawData" => "",
                    "Type" => "UNKNOWN",
                    "Reply" => null,
                    "Checksum" => "00",
                    "CalcChecksum" => "00",
                ),
                false,
            ),
        );
    }
    /**
    * test the set routine when an extra class exists
    *
    * @param array  $preload What to preload into the object
    * @param string $string  The string to feed recv
    * @param string $data    The expected return from toArray();
    * @param array  $expect  The expected return
    *
    * @return null
    *
    * @dataProvider dataRecv
    */
    public function testRecv($preload, $string, $data, $expect)
    {
        $obj = new PacketContainer($preload);
        $ret = $obj->recv($string);
        $this->assertSame($expect, $ret, "recv returned the wrong value");
        $array = $obj->toArray();
        $this->checkDateTime($array, false);
        $this->assertSame($data, $array, "The data returned is wrong");
    }
    /**
    * data provider for testUnsolicited
    *
    * @return array
    */
    public static function dataUnsolicited()
    {
        return array(
            array(
                "5A5A5A55000ABC0000200401020304C3",
                false,
            ),
            array(
                array(),
                false,
            ),
            array(
                array(
                    "To" => "000000",
                    "From" => "000020",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => "01020304",
                ),
                true,
            ),
            array(
                array(
                    "To" => "0000E1",
                    "From" => "000020",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => "01020304",
                ),
                false,
            ),
            array(
                array(
                    "To" => "000000",
                    "From" => "000020",
                    "Command" => "01",
                    "Length"  => 4,
                    "Data" => "01020304",
                ),
                false,
            ),
        );
    }
    /**
    * test the set routine when an extra class exists
    *
    * @param array $preload What to preload into the object
    * @param array $expect  The expected return
    *
    * @return null
    *
    * @dataProvider dataUnsolicited
    */
    public function testUnsolicited($preload, $expect)
    {
        $obj = new PacketContainer($preload);
        $ret = $obj->unsolicited();
        $this->assertSame($expect, $ret);
    }
    /**
    * data provider for testReplyTime
    *
    * @return array
    */
    public static function dataReplyTime()
    {
        return array(
            array(
                array(
                    "Time" => 1.0,
                ),
                array(
                    "Time" => 2.0,
                ),
                1.0,
            ),
            array(
                array(
                    "Time" => 1.0,
                ),
                null,
                0.0,
            ),
        );
    }
    /**
    * test the set routine when an extra class exists
    *
    * @param array $preload What to preload into the object
    * @param array $reply   What to preload into the reply object
    * @param array $expect  The expected return
    *
    * @return null
    *
    * @dataProvider dataReplyTime
    */
    public function testReplyTime($preload, $reply, $expect)
    {
        $obj = new PacketContainer($preload);
        if (!is_null($reply)) {
            $obj->Reply = new PacketContainer($reply);
        }
        $ret = $obj->replyTime();
        $this->assertSame($expect, $ret);
    }
    /**
    * data provider for testToMe
    *
    * @return array
    */
    public static function dataToMe()
    {
        return array(
            array(
                "5A5A5A55000020000ABC0401020304C3",
                "000020",
                true,
            ),
            array(
                array(),
                "FE2351",
                false,
            ),
            array(
                array(
                    "To" => "000020",
                    "From" => "000ABC",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => "01020304",
                ),
                "000020",
                true,
            ),
            array(
                array(
                    "To" => "FE1293",
                    "From" => "000ABC",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => "01020304",
                ),
                "FE1293",
                true,
            ),
            array(
                array(
                    "To" => "000000",
                    "From" => "000020",
                    "Command" => "01",
                    "Length"  => 4,
                    "Data" => "01020304",
                ),
                "FE2351",
                false,
            ),
        );
    }
    /**
    * test the set routine when an extra class exists
    *
    * @param array  $preload What to preload into the object
    * @param string $myID    The ID to load into the socket
    * @param array  $expect  The expected return
    *
    * @return null
    *
    * @dataProvider dataToMe
    */
    public function testToMe($preload, $myID, $expect)
    {
        $this->config->sockets->forceDeviceID($myID);
        $obj = new PacketContainer($preload);
        $ret = $obj->toMe();
        $this->assertSame($expect, $ret);
    }
    /**
    * data provider for testDeviceID
    *
    * @return array
    */
    public static function dataSend()
    {
        return array(
            // #0 packet timeout
            array(
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => "01020304",
                    "Timeout"  => 1,
                ),
                "",
                "5A5A5A55000ABC0000200401020304C3"
                ."5A5A5A55000ABC0000200401020304C3"
                ."5A5A5A03000ABC0000200095"
                ."5A5A5A55000ABC0000200401020304C3",
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => array(1,2,3,4),
                    "RawData" => "01020304",
                    "Type" => "SENSORREAD",
                    "Reply" => null,
                    "Checksum" => "C3",
                    "CalcChecksum" => "C3",
                ),
                "default",
            ),
            // #1 Good Reply
            array(
                "5A5A5A55000ABC0000200401020304C3",
                "5A5A5A55000ABC0000200401020304C3A134389105239258"
                ."5A5A5A01000020000ABC040102030497",
                "5A5A5A55000ABC0000200401020304C3",
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => array(1,2,3,4),
                    "RawData" => "01020304",
                    "Type" => "SENSORREAD",
                    "Reply" => array(
                        "To" => "000020",
                        "From" => "000ABC",
                        "Command" => "01",
                        "Length"  => 4,
                        "Data" => array(1,2,3,4),
                        "RawData" => "01020304",
                        "Type" => "REPLY",
                        "Reply" => null,
                        "Checksum" => "97",
                        "CalcChecksum" => "97",
                    ),
                    "Checksum" => "C3",
                    "CalcChecksum" => "C3",
                ),
                "default",
            ),
            // #2 Good Reply
            array(
                "5A5A5A030000200000E10401020304C2",
                "5A5A5A010000E10000200401020304C0",
                "5A5A5A030000200000E10401020304C2",
                array(
                    "To" => "000020",
                    "From" => "0000E1",
                    "Command" => "03",
                    "Length"  => 4,
                    "Data" => array(1,2,3,4),
                    "RawData" => "01020304",
                    "Type" => "FINDPING",
                    "Reply" => array(
                        "To" => "0000E1",
                        "From" => "000020",
                        "Command" => "01",
                        "Length"  => 4,
                        "Data" => array(1,2,3,4),
                        "RawData" => "01020304",
                        "Type" => "REPLY",
                        "Reply" => null,
                        "Checksum" => "C0",
                        "CalcChecksum" => "C0",
                    ),
                    "Checksum" => "C2",
                    "CalcChecksum" => "C2",
                ),
                "default",
            ),
            // #3 Good Reply (Reply already loaded)
            array(
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Data" => "01020304",
                    "Checksum" => "C3",
                    "group" => "default",
                    "Reply" => new PacketContainer(
                        array(
                            "From" => "000ABC",
                            "To" => "000020",
                            "Command" => "01",
                            "Data" => "01020304",
                            "Checksum" => "C3",
                            "group" => "other",
                            "Timeout" => 1,
                        )
                    ),
                    "Timeout" => 1,
                ),
                //"5A5A5A55000ABC0000200401020304C3A134389105239258".
                "5A5A5A01000020000ABC040102030497",
                "5A5A5A55000ABC0000200401020304C3",
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => array(1,2,3,4),
                    "RawData" => "01020304",
                    "Type" => "SENSORREAD",
                    "Reply" => array(
                        "To" => "000020",
                        "From" => "000ABC",
                        "Command" => "01",
                        "Length"  => 4,
                        "Data" => array(1,2,3,4),
                        "RawData" => "01020304",
                        "Type" => "REPLY",
                        "Reply" => null,
                        "Checksum" => "97",
                        "CalcChecksum" => "97",
                    ),
                    "Checksum" => "C3",
                    "CalcChecksum" => "C3",
                ),
                "default",
            ),
            // #4 Good Reply alt socket
            array(
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Data" => "01020304",
                    "Checksum" => "C3",
                    "group" => "other",
                    "Timeout" => 3,
                ),
                "5A5A5A01000020000ABC040102030497",
                "5A5A5A55000ABC0000200401020304C3",
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => array(1,2,3,4),
                    "RawData" => "01020304",
                    "Type" => "SENSORREAD",
                    "Reply" => array(
                        "To" => "000020",
                        "From" => "000ABC",
                        "Command" => "01",
                        "Length"  => 4,
                        "Data" => array(1,2,3,4),
                        "RawData" => "01020304",
                        "Type" => "REPLY",
                        "Reply" => null,
                        "Checksum" => "97",
                        "CalcChecksum" => "97",
                    ),
                    "Checksum" => "C3",
                    "CalcChecksum" => "C3",
                ),
                "other",
            ),
            // #5 No reply expected (Bad reply already loaded)
            array(
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => "01020304",
                    "GetReply" => false,
                    "Reply" => new PacketContainer(
                        array(
                            "To" => "000ABC",
                            "From" => "000020",
                            "Command" => "55",
                            "Data" => "01020304",
                            "Checksum" => "C3",
                            "group" => "other",
                            "Timeout" => 1,
                        )
                    ),
                ),
                "",
                "5A5A5A55000ABC0000200401020304C3",
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => array(1,2,3,4),
                    "RawData" => "01020304",
                    "Type" => "SENSORREAD",
                    "Reply" => null,
                    "Checksum" => "C3",
                    "CalcChecksum" => "C3",
                ),
                "default",
            ),
            // #6 No reply expected
            array(
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => "01020304",
                    "GetReply" => false,
                ),
                "",
                "5A5A5A55000ABC0000200401020304C3",
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => array(1,2,3,4),
                    "RawData" => "01020304",
                    "Type" => "SENSORREAD",
                    "Reply" => null,
                    "Checksum" => "C3",
                    "CalcChecksum" => "C3",
                ),
                "default",
            ),
            // #7 No reply expected (find ping sent)
            array(
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => "01020304",
                    "GetReply" => false,
                    "Retries" => 2,  // This causes the findping
                ),
                "",
                "5A5A5A55000ABC0000200401020304C35A5A5A03000ABC0000200095",
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => array(1,2,3,4),
                    "RawData" => "01020304",
                    "Type" => "SENSORREAD",
                    "Reply" => null,
                    "Checksum" => "C3",
                    "CalcChecksum" => "C3",
                ),
                "default",
            ),
        );
    }
    /**
    * test the set routine when an extra class exists
    *
    * @param array  $preload     The value to preload
    * @param string $readString  This is the string that will be returned from
    *                            the socket
    * @param string $writeString This is what the socket write string should
    *                            look like
    * @param array  $expect      The expected return
    * @param string $group       The group to expect
    *
    * @return null
    *
    * @dataProvider dataSend
    */
    public function testSend($preload, $readString, $writeString, $expect, $group)
    {
        $this->socket[$group]->readString = $readString;

        $obj = new PacketContainer($preload);
        $obj->send();
        $this->checkTestSend(
            $obj,
            $preload,
            $readString,
            $writeString,
            $expect,
            $group
        );
    }
    /**
    * data provider for testIsEmpty
    *
    * @return array
    */
    public static function dataIsEmpty()
    {
        return array(
            array(
                array(
                ),
                true,
            ),
            array(
                array(
                    "To" => "123456",
                    "From" => "123456",
                ),
                false,
            ),
        );
    }
    /**
    * test the isEmpty method
    *
    * @param array  $preload Data to preload
    * @param string $expect  The expected return
    *
    * @return null
    *
    * @dataProvider dataIsEmpty
    */
    public function testIsEmpty($preload, $expect)
    {
        $obj = new PacketContainer($preload);
        $ret = $obj->isEmpty();
        $this->assertSame(
            $expect,
            $ret
        );
    }
    /**
    * data provider for testSame
    *
    * @return array
    */
    public static function dataSame()
    {
        return array(
            array(
                array(
                    "Date" => "2004-02-28 01:02:03",
                ),
                array(
                    "Date" => "2004-02-28 01:02:03",
                ),
                true,
            ),
            array(
                array(
                    "To" => "123456",
                    "From" => "123456",
                    "Command" => "5B",
                    "Data" => "010203",
                    "Date" => "2004-02-28 01:02:03",
                ),
                array(
                    "To" => "123456",
                    "From" => "123456",
                    "Command" => "5B",
                    "Data" => "010203",
                    "Date" => "2004-02-28 01:02:03",
                ),
                true,
            ),
            array(
                array(
                    "To" => "123456",
                    "From" => "123456",
                    "Command" => "5B",
                    "Data" => "010203",
                    "Date" => "2009-02-28 01:02:03",
                ),
                array(
                    "To" => "123456",
                    "From" => "123456",
                    "Command" => "5B",
                    "Data" => "0102",
                    "Date" => "2009-02-28 01:02:03",
                ),
                false,
            ),
        );
    }
    /**
    * test the isEmpty method
    *
    * @param array  $preload  Data to preload
    * @param array  $preload2 Data to preload
    * @param string $expect   The expected return
    *
    * @return null
    *
    * @dataProvider dataSame
    */
    public function testSame($preload, $preload2, $expect)
    {
        $this->o->fromAny($preload);
        $pkt = new PacketContainer($preload2);
        $ret = $this->o->Same($pkt);
        $this->assertSame($expect, $ret);
    }
    /**
    * data provider for testTimeout
    *
    * @return array
    */
    public static function dataTimeout()
    {
        return array(
            array(
                array(
                ),
                false,
            ),
            array(
                array(
                    "To" => "123456",
                    "From" => "123456",
                    "Command" => "5B",
                    "Data" => "010203",
                    "Date" => date("Y-m-d H:i:s"),
                    "Timeout" => 1000000,
                ),
                false,
            ),
            array(
                array(
                    "To" => "123456",
                    "From" => "123456",
                    "Command" => "5B",
                    "Data" => "010203",
                    "Date" => "2003-02-25 00:00:00",
                ),
                true,
            ),
        );
    }
    /**
    * test the timeout method
    *
    * @param array  $preload Data to preload
    * @param string $expect  The expected return
    *
    * @return null
    *
    * @dataProvider dataTimeout
    */
    public function testTimeout($preload, $expect)
    {
        $pkt = new PacketContainer($preload);
        $ret = $pkt->Timeout();
        $this->assertSame($expect, $ret);
    }

    /**
    * data provider for testDeviceID
    *
    * @return array
    */
    public static function dataPing()
    {
        return array(
            // packet timeout
            array(
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => "01020304",
                    "Timeout"  => 1,
                ),
                "",
                "5A5A5A02000ABC000020040102030494"
                ."5A5A5A02000ABC000020040102030494"
                ."5A5A5A03000ABC0000200095"
                ."5A5A5A02000ABC000020040102030494",
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "02",
                    "Length"  => 4,
                    "Data" => array(1,2,3,4),
                    "RawData" => "01020304",
                    "Type" => "PING",
                    "Reply" => null,
                    "Checksum" => "C3",
                    "CalcChecksum" => "94",
                ),
                false,
                "default",
            ),
            // Good Reply
            array(
                "5A5A5A55000ABC0000200401020304C3",
                "5A5A5A55000ABC0000200401020304C3A134389105239258"
                ."5A5A5A01000020000ABC040102030497",
                "5A5A5A02000ABC000020040102030494",
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "02",
                    "Length"  => 4,
                    "Data" => array(1,2,3,4),
                    "RawData" => "01020304",
                    "Type" => "PING",
                    "Reply" => array(
                        "To" => "000020",
                        "From" => "000ABC",
                        "Command" => "01",
                        "Length"  => 4,
                        "Data" => array(1,2,3,4),
                        "RawData" => "01020304",
                        "Type" => "REPLY",
                        "Reply" => null,
                        "Checksum" => "97",
                        "CalcChecksum" => "97",
                    ),
                    "Checksum" => "C3",
                    "CalcChecksum" => "94",
                ),
                false,
                "default",
            ),
            // Good Reply, findping
            array(
                "5A5A5A55000ABC0000200401020304C3",
                "5A5A5A55000ABC0000200401020304C3A134389105239258"
                ."5A5A5A01000020000ABC040102030497",
                "5A5A5A03000ABC000020040102030495",
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "03",
                    "Length"  => 4,
                    "Data" => array(1,2,3,4),
                    "RawData" => "01020304",
                    "Type" => "FINDPING",
                    "Reply" => array(
                        "To" => "000020",
                        "From" => "000ABC",
                        "Command" => "01",
                        "Length"  => 4,
                        "Data" => array(1,2,3,4),
                        "RawData" => "01020304",
                        "Type" => "REPLY",
                        "Reply" => null,
                        "Checksum" => "97",
                        "CalcChecksum" => "97",
                    ),
                    "Checksum" => "C3",
                    "CalcChecksum" => "95",
                ),
                true,
                "default",
            ),
            // No reply expected
            array(
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => "01020304",
                    "GetReply" => false,
                ),
                "",
                "5A5A5A02000ABC000020040102030494",
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "02",
                    "Length"  => 4,
                    "Data" => array(1,2,3,4),
                    "RawData" => "01020304",
                    "Type" => "PING",
                    "Reply" => null,
                    "Checksum" => "C3",
                    "CalcChecksum" => "94",
                ),
                false,
                "default",
            ),
        );
    }
    /**
    * test the set routine when an extra class exists
    *
    * @param array  $preload     The value to preload
    * @param string $readString  This is the string that will be returned from
    *                            the socket
    * @param string $writeString This is what the socket write string should
    *                            look like
    * @param array  $expect      The expected return
    * @param bool   $find        If true a findping is used
    * @param string $group       The group to send the data out on
    *
    * @return null
    *
    * @dataProvider dataPing
    */
    public function testPing(
        $preload,
        $readString,
        $writeString,
        $expect,
        $find,
        $group
    ) {
        $this->socket["default"]->readString = $readString;
        $obj = new PacketContainer($preload);
        $obj->ping("", $find);
        $this->checkTestSend(
            $obj, $preload, $readString, $writeString, $expect, $group
        );
    }

    /**
    * data provider for testMonitor
    *
    * @return array
    */
    public static function dataMonitor()
    {
        return array(
            // multiple packets in queue (should return the first)
            array(
                array(
                ),
                "5A5A5A55000ABC0000200401020304C3"
                ."5A5A5A55000ABC0000200401020304C3"
                ."5A5A5A55000ABC0000200401020304C3",
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => array(1,2,3,4),
                    "RawData" => "01020304",
                    "Type" => "SENSORREAD",
                    "Reply" => null,
                    "Checksum" => "C3",
                    "CalcChecksum" => "C3",
                ),
            ),
            // One packet
            array(
                array(
                    "GetReply" => false,
                ),
                "5A5A5A55000ABC0000200401020304C3",
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => array(1,2,3,4),
                    "RawData" => "01020304",
                    "Type" => "SENSORREAD",
                    "Reply" => null,
                    "Checksum" => "C3",
                    "CalcChecksum" => "C3",
                ),
            ),
            // Nothing
            array(
                array(
                    "GetReply" => false,
                    "Timeout"  => 1,
                ),
                "",
                false,
            ),
        );
    }
    /**
    * Tests the packet monitor
    *
    * @param array  $preload    The value to preload
    * @param string $readString This is the string that will be returned from
    *                           the socket
    * @param array  $expect     The expected return
    *
    * @return null
    *
    * @dataProvider dataMonitor
    */
    public function testMonitor($preload, $readString, $expect)
    {
        $this->socket["default"]->readString = $readString;
        $obj = PacketContainer::monitor($preload);
        if (is_object($obj)) {
            $ret = $obj->toArray();
            $this->checkDateTime($ret);
        } else {
            $ret = $obj;
        }
        $this->assertSame($expect, $ret);
    }
    /**
    * data provider for testMyReply
    *
    * @return array
    */
    public static function dataMyReply()
    {
        return array(
            // Good reply
            array(
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Time" => 12341.1234,
                    "Data" => "01020304",
                ),
                array(
                    "To" => "000020",
                    "From" => "000ABC",
                    "Command" => "01",
                    "Time" => 12341.1235,
                    "Data" => "01020304",
                ),
                true
            ),
            // Bad reply.  Reply dated before packet
            array(
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Time" => 12341.1234,
                    "Data" => "01020304",
                ),
                array(
                    "To" => "000020",
                    "From" => "000ABC",
                    "Command" => "01",
                    "Time" => 12341.1233,
                    "Data" => "01020304",
                ),
                false
            ),
            // Bad reply.  Reply dated same as before packet
            array(
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Time" => 12341.1234,
                    "Data" => "01020304",
                ),
                array(
                    "To" => "000020",
                    "From" => "000ABC",
                    "Command" => "01",
                    "Time" => 12341.1234,
                    "Data" => "01020304",
                ),
                false
            ),
            // No original packet
            array(
                array(
                ),
                array(
                    "To" => "000020",
                    "From" => "000ABC",
                    "Command" => "01",
                    "Time" => 12341.1234,
                    "Data" => "01020304",
                ),
                false
            ),
            // No Reply
            array(
                array(
                    "To" => "000ABC",
                    "From" => "000020",
                    "Command" => "55",
                    "Time" => 12341.1234,
                    "Data" => "01020304",
                ),
                array(
                ),
                false
            ),
            // Nothing
            array(
                array(
                ),
                array(
                ),
                false,
            ),
        );
    }
    /**
    * test the set routine when an extra class exists
    *
    * @param array $preload The value to preload
    * @param array $reply   The reply packet
    * @param bool  $expect  The expected return
    *
    * @return null
    *
    * @dataProvider dataMyReply
    */
    public function testMyReply($preload, $reply, $expect)
    {
        $this->o->fromAny($preload);
        $obj = new PacketContainer($reply);
        $this->assertSame($expect, $this->o->myReply($obj));
    }

    /**
    * data provider for testReply
    *
    * @return array
    */
    public static function dataReply()
    {
        return array(
            array(
                array(
                    "To" => "000020",
                    "From" => "000ABC",
                    "Command" => "55",
                    "Length"  => 4,
                    "Data" => "01020304",
                    "Timeout"  => 1,
                ),
                "",
                "5A5A5A01000ABC0000200097",
                true,
            ),
            array(
                "5A5A5A55000020000ABC0401020304C3",
                "01020304",
                "5A5A5A01000ABC000020040102030497",
                true,
            ),
        );
    }
    /**
    * test the set routine when an extra class exists
    *
    * @param array  $preload     The value to preload
    * @param string $replyString This is the string of data for our packet
    * @param string $writeString This is what the socket write string should
    *                            look like
    * @param array  $expect      The expected return
    *
    * @return null
    *
    * @dataProvider dataReply
    */
    public function testReply($preload, $replyString, $writeString, $expect)
    {
        $obj = new PacketContainer($preload);
        $ret = $obj->reply($replyString);
        $this->assertSame($expect, $ret);
        $this->assertSame($writeString, $this->socket["default"]->writeString);
    }
    /**
    * data provider for testReply
    *
    * @return array
    */
    public static function dataPowerup()
    {
        return array(
            array(
                "",
                "5A5A5A5E000000000020007E",
                true,
            ),
            array(
                "01020304",
                "5A5A5A5E00000000002004010203047E",
                true,
            ),
        );
    }
    /**
    * test the set routine when an extra class exists
    *
    * @param string $replyString This is the string of data for our packet
    * @param string $writeString This is what the socket write string should
    *                            look like
    * @param array  $expect      The expected return
    *
    * @return null
    *
    * @dataProvider dataPowerup
    */
    public function testPowerup($replyString, $writeString, $expect)
    {
        $ret = PacketContainer::powerup($replyString);
        $this->assertSame($expect, $ret);
        $this->assertSame($writeString, $this->socket["default"]->writeString);
    }


    /**
    * test the set routine when an extra class exists
    *
    * @param array  $preload     The value to preload
    * @param string $readString  This is the string that will be returned from
    *                            the socket
    * @param string $writeString This is what the socket write string should
    *                            look like
    * @param array  $expect      The expected return
    *
    * @return null
    *
    * @dataProvider dataSend
    */
    public function testSendBadSocket($preload, $readString, $writeString, $expect)
    {
        $this->socket["default"] = null;
        $obj = new PacketContainer($preload);
        $ret = $obj->send();
        $this->assertFalse($ret);
    }


    /**
    * test the set routine when an extra class exists
    *
    * @param object &$obj        The object to check
    * @param array  $preload     The value to preload
    * @param string $readString  This is the string that will be returned from
    *                            the socket
    * @param string $writeString This is what the socket write string should
    *                            look like
    * @param array  $expect      The expected return
    * @param string $group       The group to send the data out on
    *
    * @return null
    *
    * @dataProvider dataSend
    */
    public function checkTestSend(
        &$obj,
        $preload,
        $readString,
        $writeString,
        $expect,
        $group = "default"
    ) {
        if (is_array($expect)) {
            // First make sure we got an object back.
            $this->assertInternalType("object", $obj, "Type wrong");
            $ret = $obj->toArray();
            $this->checkDateTime($ret);
            $this->assertSame($expect, $ret, "Incorrect Date");
            $this->assertSame(
                $writeString,
                $this->socket[$group]->writeString,
                "Write string wrong"
            );
        } else {
            $this->assertFalse($obj);
        }
    }
    /**
    * Checks the 'Date' and 'Time' fields, unsetting them afterwards
    *
    * @param object &$ret      The output of toArray()
    * @param bool   $checkTime Check to see if the time is > 0
    *
    * @return null
    *
    * @dataProvider dataSend
    */
    public function checkDateTime(&$ret, $checkTime = true)
    {
        // Test the date separately
        $this->assertInternalType("int", $ret["Date"], "Date must be an int");
        if ($checkTime) {
            $this->assertThat(
                $ret["Date"],
                $this->greaterThan(0),
                "Date must be greater than zero"
            );
        }
        unset($ret["Date"]);
        // Test the time separately
        $this->assertInternalType("float", $ret["Time"], "Time must be a float");
        if ($checkTime) {
            $this->assertThat(
                $ret["Time"],
                $this->greaterThan(0),
                "Time must be greater than zero"
            );
        }
        unset($ret["Time"]);
        // Now check the reply, if there is one
        if (is_array($ret["Reply"])) {
            $this->assertInternalType(
                "int",
                $ret["Reply"]["Date"],
                "Date must be an int"
            );
            if ($checkTime) {
                $this->assertThat(
                    $ret["Reply"]["Date"],
                    $this->greaterThan(0),
                    "Date must be greater than zero"
                );
            }
            unset($ret["Reply"]["Date"]);
            // Test the time separately
            $this->assertInternalType(
                "float",
                $ret["Reply"]["Time"],
                "Reply Time must be a float"
            );
            if ($checkTime) {
                $this->assertThat(
                    $ret["Reply"]["Time"],
                    $this->greaterThan(0),
                    "Reply time must be greater than 0"
                );
            }
            unset($ret["Reply"]["Time"]);
        }
    }
    /**
    * data provider for testDeviceID
    *
    * @return array
    */
    public static function dataToPktString()
    {
        return array(
            array(
                array(
                    "Command" => "55",
                    "To" => "ABC",
                    "From" => "000020",
                    "Data" => "01020304",
                ),
                "5A5A5A55000ABC0000200401020304C3",
            ),
            array(
                array(
                    "Command" => "5C",
                    "To" => "000ABC",
                    "From" => "000020",
                    "Data" => "",
                ),
                "5A5A5A5C000ABC00002000CA",
            ),
            array(
                array(
                    "Command" => "5C",
                    "To" => "12345ABCDEF",
                    "From" => "000020",
                    "Data" => "",
                    "Length" => 0,
                    "Checksum" => "F5",
                ),
                "5A5A5A5CABCDEF00002000F5",
            ),
            array(
                array(),
                "",
            ),
        );
    }
    /**
    * test the set routine when an extra class exists
    *
    * @param array $preload The value to preload
    * @param array $expect  The expected return
    *
    * @return null
    *
    * @dataProvider dataToPktString
    */
    public function testToPktString($preload, $expect)
    {
        $this->o->fromArray($preload);
        $this->assertSame($expect, $this->o->toPktString());

    }

    /**
    * This tests to make sure we are setting the group correctly with a default
    * if an empty string is given.
    *
    * @return null
    */
    public function testSetGroup()
    {
        unset($this->config->useSocket);
        $this->o->group = "";
        $this->assertSame("default", $this->o->group);

    }
    /**
    * data provider for testSet
    *
    * @return array
    */
    public static function dataSet()
    {
        return array(
            array("Timeout", 0, 5),
            array("Timeout", 1, 1),
            array("Date", "2010-04-25 13:42:23", 1272202943),
            array("Date", "2010-04-25", 1272153600),
            array("Date", "Sun, 25 April 2010, 1:42:23pm", 1272202943),
            array("Date", 1234567890, 1234567890),
            array("Date", "1234567890", 1234567890),
            array("Date", "This is not a date", 0),
        );
    }

    /**
    * test the set routine when an extra class exists
    *
    * @param string $var    The variable to set
    * @param mixed  $value  The value to set
    * @param mixed  $expect The expected return
    *
    * @return null
    *
    * @dataProvider dataSet
    */
    public function testSet($var, $value, $expect)
    {
        $this->o->$var = $value;
        $data = $this->readAttribute($this->o, "data");
        $this->assertSame($expect, $data[$var]);
    }
    /**
    * test the set routine when an extra class exists
    *
    * @return null
    */
    public function testGetDeviceID()
    {
        $id = PacketContainer::tempDeviceID();
        $this->assertThat(
            $id, $this->greaterThanOrEqual(PacketContainer::MIN_SN)
        );
        $this->assertThat(
            $id, $this->lessThanOrEqual(PacketContainer::MAX_SN)
        );
    }

    /**
    * data provider for testSet
    *
    * @return array
    */
    public static function dataCheckDeviceID()
    {
        return array(
            array(PacketContainer::MIN_SN - 1, false),
            array(PacketContainer::MAX_SN + 1, false),
            array(PacketContainer::MIN_SN, true),
            array(PacketContainer::MAX_SN, true),
            array(dechex(PacketContainer::MIN_SN - 1), false),
            array(dechex(PacketContainer::MAX_SN + 1), false),
            array(dechex(PacketContainer::MIN_SN), true),
            array(dechex(PacketContainer::MAX_SN), true),
        );
    }

    /**
    * test the set routine when an extra class exists
    *
    * @param mixed $value  The value to set
    * @param mixed $expect The expected return
    *
    * @return null
    *
    * @dataProvider dataCheckDeviceID
    */
    public function testCheckDeviceID($value, $expect)
    {
        $this->assertSame($expect, PacketContainer::checkDeviceID($value));
    }

}

?>
