<?php
/**
 * Tests the filter class
 *
 * PHP Version 5
 *
 * <pre>
 * HUGnetLib is a library of HUGnet code
 * Copyright (C) 2007-2010 Hunt Utilities Group, LLC
 * Copyright (C) 2009 Scott Price
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 * </pre>
 *
 * @category   Devices
 * @package    HUGnetLibTest
 * @subpackage Devices
 * @author     Scott Price <prices@hugllc.com>
 * @copyright  2007-2010 Hunt Utilities Group, LLC
 * @copyright  2009 Scott Price
 * @license    http://opensource.org/licenses/gpl-license.php GNU Public License
 * @version    SVN: $Id$
 * @link       https://dev.hugllc.com/index.php/Project:HUGnetLib
 *
 */

// Need to make sure this file is not added to the code coverage
PHPUnit_Util_Filter::addFileToFilter(__FILE__);
require_once dirname(__FILE__)."/../PluginTestBase.php";
/**
 * Test class for filter.
 * Generated by PHPUnit_Util_Skeleton on 2007-10-30 at 08:44:56.
 *
 * @category   Devices
 * @package    HUGnetLibTest
 * @subpackage Devices
 * @author     Scott Price <prices@hugllc.com>
 * @copyright  2007-2010 Hunt Utilities Group, LLC
 * @copyright  2009 Scott Price
 * @license    http://opensource.org/licenses/gpl-license.php GNU Public License
 * @link       https://dev.hugllc.com/index.php/Project:HUGnetLib
 */
abstract class DevicePluginTestBase extends PluginTestBase
{
    /**
    * test the set routine when an extra class exists
    *
    * @param array  $obj  The object to work with
    * @param string $name The name of the index
    * @param array  $col  The column array
    *
    * @return null
    *
    * @dataProvider dataRegisterPlugin
    */
    public function testRegisterPluginDevices($class)
    {
        $var = eval("return $class::\$registerPlugin;");
        $this->assertType(
            "array",
            $var["Devices"],
            "Devices is not an array"
        );
        foreach ($var["Devices"] as $fw => $hard) {
            $this->assertRegExp(
                "/([0-9]{4}-[0-9]{2}-[0-9]{2}-[A-Z]|DEFAULT)/",
                $fw,
                "firmware $fw is not in the correct form"
            );
            $this->assertType(
                "array",
                $hard,
                "hardware $fw is not an array"
            );
            foreach ($hard as $hw => $ver) {
                $this->assertRegExp(
                    "/([0-9]{4}-[0-9]{2}-[0-9]{2}-[A-Z]|DEFAULT|VIRTUAL)/",
                    $hw,
                    "hardware $hw is not in the correct form"
                );
                $this->assertType(
                    "string",
                    $ver,
                    "version $hw is not a string"
                );
                $dev = explode(",", $ver);
                foreach ($dev as $d) {
                    $this->assertRegExp(
                        "/([0-9]{1,2}\.[0-9]{1,2}\.[0-9]{1,2}|DEFAULT|BAD)/",
                        $d,
                        "Version $d is not in the correct form"
                    );
                }

            }
        }
    }

}

?>
