<?php
/**
 * Tests the filter class
 *
 * PHP Version 5
 *
 * <pre>
 * HUGnetLib is a library of HUGnet code
 * Copyright (C) 2014 Hunt Utilities Group, LLC
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 * </pre>
 *
 * @category   Libraries
 * @package    HUGnetLibTest
 * @subpackage SuiteTables
 * @author     Scott Price <prices@hugllc.com>
 * @copyright  2014 Hunt Utilities Group, LLC
 * @license    http://opensource.org/licenses/gpl-license.php GNU Public License
 * @link       http://dev.hugllc.com/index.php/Project:HUGnetLib
 *
 */
namespace HUGnet\db\tables;
/** This is a required class */
require_once CODE_BASE.'db/Table.php';
/** This is a required class */
require_once CODE_BASE.'db/Connection.php';
/** This is a required class */
require_once CODE_BASE.'db/tables/Firmware.php';
/** This is a required class */
require_once TEST_BASE."db/tables/TableTestBase.php";
/** This is a required class */
require_once CODE_BASE.'system/System.php';
/** This is a required class */
require_once CODE_BASE.'system/Device.php';
/** This is a required class */
require_once TEST_CONFIG_BASE.'stubs/DummySystem.php';
/**
 * Test class for filter.
 * Generated by PHPUnit_Util_Skeleton on 2007-10-30 at 08:44:56.
 *
 * @category   Libraries
 * @package    HUGnetLibTest
 * @subpackage SuiteTables
 * @author     Scott Price <prices@hugllc.com>
 * @copyright  2014 Hunt Utilities Group, LLC
 * @license    http://opensource.org/licenses/gpl-license.php GNU Public License
 * @version    Release: 0.14.3
 * @link       http://dev.hugllc.com/index.php/Project:HUGnetLib
 */
class FirmwareTest extends TableTestBase
{

    /**
    * Sets up the fixture, for example, open a network connection.
    * This method is called before a test is executed.
    *
    * @return null
    *
    * @access protected
    */
    protected function setUp()
    {
        $this->config = array(
            "System" => array(
                "get" => array(
                    "servers" => array(
                        array(
                            "driver" => "sqlite",
                            "file" => ":memory:",
                            "group" => "default",
                        ),
                    ),
                    "verbose" => 0,
                ),
            ),
        );
        $this->system = new \HUGnet\DummySystem("System");
        $this->system->resetMock($this->config);
        $this->connect = \HUGnet\db\Connection::factory($this->system);
        $this->pdo = &$this->connect->getDBO("default");
        $data = array(
        );
        $this->o = \HUGnet\db\Table::factory(
            $this->system, $data, "Firmware", $this->connect
        );
        parent::Setup();
    }
    /**
    * This gets us our database preload
    *
    * @access protected
    *
    * @return null
    */
    protected function getDataSet()
    {
        return $this->createXMLDataSet(
            TEST_CONFIG_BASE.'files/FirmwareTableTest.xml'
        );
    }

    /**
    * Tears down the fixture, for example, close a network connection.
    * This method is called after a test is executed.
    *
    * @return null
    *
    * @access protected
    */
    protected function tearDown()
    {
        $this->o = null;
        $this->config = null;
    }
    /**
    * data provider for testDeviceID
    *
    * @return array
    */
    public static function dataColumns()
    {
        $system = new \HUGnet\DummySystem("System");
        $connect = \HUGnet\db\Connection::factory($system);
        $obj = \HUGnet\db\Table::factory(
            $system, $data, "Firmware", $connect
        );
        return TableTestBase::splitObject($obj, "sqlColumns");
    }
    /**
    * data provider for testDeviceID
    *
    * @return array
    */
    public static function dataIndexes()
    {
        $system = new \HUGnet\DummySystem("System");
        $connect = \HUGnet\db\Connection::factory($system);
        $obj = \HUGnet\db\Table::factory(
            $system, $data, "Firmware", $connect
        );
        return TableTestBase::splitObject($obj, "sqlIndexes");
    }
    /**
    * data provider for testDeviceID
    *
    * @return array
    */
    public static function dataVars()
    {
        $system = new \HUGnet\DummySystem("System");
        $connect = \HUGnet\db\Connection::factory($system);
        return array(
            array(
                \HUGnet\db\Table::factory(
                    $system, $data, "Firmware", $connect
                )
            ),
        );
    }

    /**
    * data provider for testToFile
    *
    * @return array
    */
    public static function dataToFile()
    {
        return array(
            array(
                // Everything works
                array(
                    "HWPartNum" => "0039-21-01-A",
                    "FWPartNum" => "0039-20-01-C",
                    "Version" => "1.2.3",
                    "Code" => "asdf",
                    "Data" => "fsda",
                    "RelStatus" => 8,
                    "Target" => "mega16",
                ),
                sys_get_temp_dir(),
                "00392101-00392001C-1.2.3.gz",
                true,
            ),
            array(
                // No HWPartNum Specified
                array(
                    "HWPartNum" => "0039-21-01-A",
                    "FWPartNum" => "0039-20-01-C",
                    "Version" => "1.2.3",
                    "Code" => "asdf",
                    "Data" => "fsda",
                    "RelStatus" => 8,
                    "Target" => "mega16",
                ),
                "/this/is/a/dir/that/should/never/exist",
                "00392001C-1.2.3.gz",
                false,
            ),
        );
    }

    /**
    * test the set routine when an extra class exists
    *
    * @param array  $preload  The value to preload
    * @param string $path     The file path to use
    * @param string $filename The filename to check for
    * @param bool   $expect   The expected return
    *
    * @return null
    *
    * @dataProvider dataToFile
    */
    public function testToFile($preload, $path, $filename, $expect)
    {
        @unlink($path."/".$filename);
        $this->o->fromArray($preload);
        $ret = @$this->o->toFile($path);
        $this->assertSame($expect, $ret);
        if ($expect) {
            $this->assertTrue(file_exists($path."/".$filename));
            $stuff = implode("", gzfile($path."/".$filename));
            @unlink($path."/".$filename);
            $this->assertSame(
                $this->o->toString(), $stuff, "File contents wrong"
            );
        } else {
            $this->assertFalse(file_exists($path."/".$filename));
        }
    }
    /**
    * data provider for testFromFile
    *
    * @return array
    */
    public static function dataFromFile()
    {
        return array(
            array(
                // Everything works
                null,
                TEST_CONFIG_BASE."files",
                "MD5 (003921-00392001C-00.01.04.gz) = "
                ."84b01697b6fbc32c457d3b9815585fe0",
                true,
                array(
                    "group" => "default",
                    "filename" => "003921-00392001C-00.01.04.gz",
                    "id" => "37",
                    "Version" => "0.1.4",
                    "CodeHash" => "14c1839ee1c69da903a49165693d8ff2",
                    "DataHash" => "ff0091534269deecbe6dfcecc652664f",
                    "FWPartNum" => "0039-20-01-C",
                    "HWPartNum" => "0039-21",
                    "Date" => 1172579985,
                    "FileType" => "SREC",
                    "RelStatus" => 8,
                    "Tag" => "f00392001-00-01-04",
                    "Target" => "atmega16",
                    "Active" => "1",
                    "md5" => "84b01697b6fbc32c457d3b9815585fe0",
                ),
                true,
            ),
            array(
                // Everything works
                null,
                TEST_CONFIG_BASE."files",
                "003921-00392001C-00.01.04.gz",
                true,
                array(
                    "group" => "default",
                    "filename" => "003921-00392001C-00.01.04.gz",
                    "id" => "37",
                    "Version" => "0.1.4",
                    "CodeHash" => "14c1839ee1c69da903a49165693d8ff2",
                    "DataHash" => "ff0091534269deecbe6dfcecc652664f",
                    "FWPartNum" => "0039-20-01-C",
                    "HWPartNum" => "0039-21",
                    "Date" => 1172579985,
                    "FileType" => "SREC",
                    "RelStatus" => 8,
                    "Tag" => "f00392001-00-01-04",
                    "Target" => "atmega16",
                    "Active" => "1",
                    "md5" => null,
                ),
                true,
            ),
            array(
                // Bad MD5
                null,
                TEST_CONFIG_BASE."files",
                "MD5 (003928-00392001C-00.01.04.gz) = "
                ."bd2dd61d3ef24bfab9d40c8791f3b18b",
                false,
                array(
                ),
                false,
            ),
            array(
                // No HWPartNum Specified
                null,
                "/this/is/a/dir/that/should/never/exist",
                "00392001C-1.2.3.gz",
                false,
                array(),
                false,
            ),
            array(
                // Stuff already set
                array(
                    "md5" => "bd2dd61d3ef24bfab9d40c8791f3b18b",
                ),
                TEST_CONFIG_BASE."files",
                "003921-00392001C-00.01.04.gz",
                false,
                array(
                ),
                true,
            ),
        );
    }

    /**
    * test the set routine when an extra class exists
    *
    * @param mixed  $preload    Set to null for no preload, otherwise it is an array
    * @param string $path       The file path to use
    * @param string $filename   The filename to check for
    * @param bool   $expect     The expected return
    * @param array  $data       The data array to expect
    * @param bool   $fileExists Whether the file exists or not.
    *
    * @return null
    *
    * @dataProvider dataFromFile
    */
    public function testFromFile(
        $preload, $path, $filename, $expect, $data, $fileExists
    ) {
        $this->o->clearData();
        if (is_array($preload)) {
            $this->o->fromArray($preload);
        }
        $ret = @$this->o->fromFile($filename, $path);
        $this->assertSame($expect, $ret, "Return Wrong");
        if ($expect) {
            $theData = $this->readAttribute($this->o, "data");
            unset($theData["Code"]);
            unset($theData["Data"]);
            $this->assertSame($data, $theData, "Data is not the same");
        } else {
            $this->assertSame(
                $fileExists, file_exists($path."/".$filename), "File Exists"
            );
        }
    }
    /**
    * data provider for testSet
    *
    * @return array
    */
    public static function dataSet()
    {
        return array(
            array("Date", "2010-04-25 13:42:23", 1272202943),
            array("Date", "2010-04-25", 1272153600),
            array("Date", "Sun, 25 April 2010, 1:42:23pm", 1272202943),
            array("Date", 1234567890, 1234567890),
            array("Date", "This is not a date", 0),
            array("RelStatus", "DEV", Firmware::DEV),
            array("RelStatus", "BAD", Firmware::BAD),
            array("RelStatus", "BETA", Firmware::BETA),
            array("RelStatus", "RELEASE", Firmware::RELEASE),
            array("RelStatus", "72", 72),
            array("HWPartNum", "00392104C", "0039-21-04"),
            array("HWPartNum", "0039-21-04-C", "0039-21-04"),
            array("HWPartNum", "34523442350039-21-04-C", "0039-21-04"),
            array("FWPartNum", "00392104C", "0039-21-04-C"),
            array("FWPartNum", "0039-21-04-C", "0039-21-04-C"),
            array("FWPartNum", "34523442350039-21-04-C", "0039-21-04-C"),
            array(
                "filename",
                "MD5 (003921-00392001C-00.00.07.gz) = "
                ."104e9ba35ebb82e6c70a9909e375b8be",
                "003921-00392001C-00.00.07.gz"
            ),
            array(
                "filename",
                "003921-00392001C-00.00.07.gz",
                "003921-00392001C-00.00.07.gz"
            ),
        );
    }

    /**
    * test the set routine when an extra class exists
    *
    * @param string $var    The variable to set
    * @param mixed  $value  The value to set
    * @param mixed  $expect The expected return
    *
    * @return null
    *
    * @dataProvider dataSet
    */
    public function testSet($var, $value, $expect)
    {
        $this->o->set($var, $value);
        $data = $this->readAttribute($this->o, "data");
        $this->assertSame($expect, $data[$var]);
    }

    /**
    * data provider for testCompareVesrion
    *
    * @return array
    */
    public static function dataCheckFile()
    {
        return array(
            array(array(), "003921-00392001C-01.02.03.gz", true),
            array(
                array(),
                "MD5 (003921-00392001C-00.00.07.gz) = "
                ."104e9ba35ebb82e6c70a9909e375b8be",
                false,
            ),
            array(
                array(),
                "MD5 (003921-00392001C-01.02.03.gz) = "
                ."104e9ba35ebb82e6c70a9909e375b8be",
                true,
            ),
            // Wrong md5
            array(
                array(),
                "MD5 (003921-00392001C-01.02.03.gz) = "
                ."104e9ba35ebb82e6c70a9909e375b8bf",
                false,
            ),
            array( // null file name
                array(),
                null,
                false,
            ),
        );
    }
    /**
    * test
    *
    * @param array  $preload The value to preload
    * @param string $file    The filename to give it
    * @param bool   $expect  The expected return
    *
    * @return null
    *
    * @dataProvider dataCheckFile
    */
    function testCheckFile($preload, $file, $expect)
    {
        $this->o->clearData();
        $this->o->fromAny($preload);
        $ret = $this->o->checkFile($file);
        $this->assertEquals($expect, $ret);
    }
    /**
    * Data provider for testInsertRow
    *
    * @return array
    */
    public static function dataExists()
    {
        return array(
            array(
                array(
                    array(
                        "FWPartNum" => "0039-21-01-C",
                        "Version" => "1.2.3",
                    ),
                ),
                array(
                    "FWPartNum" => "0039-21-01-C",
                    "Version" => "1.2.3",
                ),
                true
            ),
            array(
                array(
                    array(
                        "FWPartNum" => "0039-21-01-C",
                        "Version" => "1.2.3",
                    ),
                ),
                array(
                    "FWPartNum" => "0039-21-01-C",
                    "Version" => "1.2.4",
                ),
                false
            ),
        );
    }
    /**
    * Tests the insert of a DeviceID
    *
    * @param array $preload The data to load into the database
    * @param mixed $data    The data to use
    * @param array $expect  The expected return
    *
    * @dataProvider dataExists
    *
    * @return null
    */
    public function testExists($preload, $data, $expect)
    {
        foreach ((array)$preload as $load) {
            $this->o->fromAny($load);
            $this->o->insertRow();
        }
        $this->o->clearData();
        $this->o->fromAny($data);
        $ret = $this->o->exists();
        $this->assertSame($expect, $ret);
    }

}

?>
