<?php
/**
 * Tests the filter class
 *
 * PHP Version 5
 *
 * <pre>
 * HUGnetLib is a library of HUGnet code
 * Copyright (C) 2014 Hunt Utilities Group, LLC
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 * </pre>
 *
 * @category   Libraries
 * @package    HUGnetLibTest
 * @subpackage SuiteTables
 * @author     Scott Price <prices@hugllc.com>
 * @copyright  2014 Hunt Utilities Group, LLC
 * @license    http://opensource.org/licenses/gpl-license.php GNU Public License
 * @link       http://dev.hugllc.com/index.php/Project:HUGnetLib
 *
 */
namespace HUGnet\db;
/** This is a required class */
require_once CODE_BASE.'db/Table.php';
/** This is a required class */
require_once CODE_BASE.'db/Connection.php';
/** This is a required class */
require_once CODE_BASE.'db/History.php';
/** This is a required class */
require_once CODE_BASE.'db/Table.php';
/** This is a required class */
require_once TEST_BASE."db/tables/TableTestBase.php";
/** This is a required class */
require_once CODE_BASE.'system/System.php';
/** This is a required class */
require_once CODE_BASE.'system/Device.php';
/** This is a required class */
require_once TEST_CONFIG_BASE.'stubs/DummySystem.php';
/** This is a required class */
require_once CODE_BASE.'interfaces/DBTable.php';

/**
 * Test class for filter.
 * Generated by PHPUnit_Util_Skeleton on 2007-10-30 at 08:44:56.
 *
 * @category   Libraries
 * @package    HUGnetLibTest
 * @subpackage SuiteTables
 * @author     Scott Price <prices@hugllc.com>
 * @copyright  2014 Hunt Utilities Group, LLC
 * @license    http://opensource.org/licenses/gpl-license.php GNU Public License
 * @version    Release: 0.14.8
 * @link       http://dev.hugllc.com/index.php/Project:HUGnetLib
 */
class HistoryTest extends tables\TableTestBase
{

    /**
    * Sets up the fixture, for example, open a network connection.
    * This method is called before a test is executed.
    *
    * @return null
    *
    * @access protected
    */
    protected function setUp()
    {
        $this->config = array(
            "System" => array(
                "get" => array(
                    "servers" => array(
                        array(
                            "driver" => "sqlite",
                            "file" => ":memory:",
                            "group" => "default",
                        ),
                        array(
                            "driver" => "sqlite",
                            "file" => ":memory:",
                            "group" => "remote",
                        ),
                    ),
                    "verbose" => 0,
                ),
            ),
        );
        $this->system = new \HUGnet\DummySystem("System");
        $this->system->resetMock($this->config);
        $this->connect = \HUGnet\db\Connection::factory($this->system);
        $this->pdo = &$this->connect->getDBO("default");
        $data = array(
        );
        $this->o = \HUGnet\db\Table::factory(
            $this->system, $data, "HistoryTestStub", $this->connect
        );
        parent::Setup();
    }

    /**
    * Tears down the fixture, for example, close a network connection.
    * This method is called after a test is executed.
    *
    * @return null
    *
    * @access protected
    */
    protected function tearDown()
    {
        unset($this->o);
        $this->config = null;
    }
    /**
    * This gets us our database preload
    *
    * @access protected
    *
    * @return null
    */
    protected function getDataSet()
    {
        return $this->createXMLDataSet(
            TEST_CONFIG_BASE.'files/HistoryTableBaseTest.xml'
        );
    }
    /**
    * data provider for testDeviceID
    *
    * @return array
    */
    public static function dataColumns()
    {
        $system = new \HUGnet\DummySystem("System");
        $connect = \HUGnet\db\Connection::factory($system);
        $obj = \HUGnet\db\Table::factory(
            $system, $data, "HistoryTestStub", $connect
        );
        return tables\TableTestBase::splitObject($obj, "sqlColumns");
    }
    /**
    * data provider for testDeviceID
    *
    * @return array
    */
    public static function dataIndexes()
    {
        $system = new \HUGnet\DummySystem("System");
        $connect = \HUGnet\db\Connection::factory($system);
        $obj = \HUGnet\db\Table::factory(
            $system, $data, "HistoryTestStub", $connect
        );
        return tables\TableTestBase::splitObject($obj, "sqlIndexes");
    }
    /**
    * data provider for testDeviceID
    *
    * @return array
    */
    public static function dataVars()
    {
        $system = new \HUGnet\DummySystem("System");
        $connect = \HUGnet\db\Connection::factory($system);
        return array(
            array(
                \HUGnet\db\Table::factory(
                    $system, $data, "HistoryTestStub", $connect
                )
            ),
        );
    }

    /**
    * data provider for testDeviceID
    *
    * @return array
    */
    public static function dataConstructor()
    {
        return array(
            array(
                array(
                    "id"  => 41,
                    "Date"   => "2003-02-28 01:59:00",
                    "deltaT"  => 5.2,
                    "Data0"  => 0,
                    "Data1"  => 1,
                    "Data2"  => 2,
                    "Data3"  => 3,
                    "Data4"  => 4,
                    "Data5"  => 5,
                    "Data6"  => 6,
                    "Data7"  => 7,
                    "Data8"  => 8,
                    "Data9"  => 9,
                    "Data10"  => 10,
                    "Data11"  => 11,
                    "Data12"  => 12,
                    "Data13"  => 13,
                    "Data14"  => 14,
                ),
                array(
                    "group" => "default",
                    "raw" => array(),
                    "converted" => false,
                    "id"  => 41,
                    "Date"   => 1046397540,
                    "TestID" => null,
                    "deltaT"  => 5.2,
                    "Data0"  => 0,
                    "Data1"  => 1,
                    "Data2"  => 2,
                    "Data3"  => 3,
                    "Data4"  => 4,
                    "Data5"  => 5,
                    "Data6"  => 6,
                    "Data7"  => 7,
                    "Data8"  => 8,
                    "Data9"  => 9,
                    "Data10"  => 10,
                    "Data11"  => 11,
                    "Data12"  => 12,
                    "Data13"  => 13,
                    "Data14"  => 14,
                ),
            ),
            array(
                array(
                    "id"  => 41,
                    "Date"   => "2003-02-28 01:59:00",
                    "TestID" => 5,
                    "deltaT"  => 5.2,
                    "Data0"  => 0,
                    "Data1"  => 1,
                    "Data2"  => 2,
                    "Data3"  => 3,
                    "Data4"  => 4,
                    "Data5"  => 5,
                    "Data6"  => 6,
                    "Data7"  => 7,
                    "Data8"  => 8,
                    "Data9"  => 9,
                    "Data10"  => 10,
                    "Data11"  => 11,
                    "Data12"  => 12,
                    "Data13"  => 13,
                    "Data14"  => 14,
                ),
                array(
                    "group" => "default",
                    "raw" => array(),
                    "converted" => false,
                    "id"  => 41,
                    "Date"   => 1046397540,
                    "TestID" => 5,
                    "deltaT"  => 5.2,
                    "Data0"  => 0,
                    "Data1"  => 1,
                    "Data2"  => 2,
                    "Data3"  => 3,
                    "Data4"  => 4,
                    "Data5"  => 5,
                    "Data6"  => 6,
                    "Data7"  => 7,
                    "Data8"  => 8,
                    "Data9"  => 9,
                    "Data10"  => 10,
                    "Data11"  => 11,
                    "Data12"  => 12,
                    "Data13"  => 13,
                    "Data14"  => 14,
                ),
            ),
        );
    }
    /**
    * test the set routine when an extra class exists
    *
    * @param array $preload The value to preload
    * @param array $expect  The expected return
    *
    * @return null
    *
    * @dataProvider dataConstructor
    */
    public function testConstructor($preload, $expect)
    {
        $obj = \HUGnet\db\Table::factory(
            $this->system, $preload, "HistoryTestStub", $this->connect
        );
        $this->assertSame($expect, $obj->toArray());
        unset($obj);
    }
    /**
    * data provider for testDeviceID
    *
    * @return array
    */
    public static function dataFromDataArray()
    {
        return array(
            array(
                array(
                    "group" => "remote",
                    "deltaT" => 1,
                    0 => array(
                        "value" => 1,
                        "units" => "testUnit",
                        "unitType" => "firstUnit",
                        "dataType" => "raw",
                    ),
                    1 => array(
                        "value" => 2,
                        "units" => "testUnit",
                        "unitType" => "firstUnit",
                        "dataType" => "raw",
                    ),
                    2 => array(
                        "value" => 4,
                        "units" => "testUnit",
                        "unitType" => "firstUnit",
                        "dataType" => "raw",
                    ),
                    3 => array(
                        "value" => 8,
                        "units" => "testUnit",
                        "unitType" => "firstUnit",
                        "dataType" => "diff",
                        "raw" => 1834,
                    ),
                    4 => array(
                        "value" => 16,
                        "units" => "testUnit",
                        "unitType" => "firstUnit",
                        "dataType" => "diff",
                        "raw" => 4842,
                    ),
                    5 => array(
                        "value" => 32,
                        "units" => "testUnit",
                        "unitType" => "firstUnit",
                        "dataType" => "raw",
                    ),
                    "DataIndex" => 127,
                    "timeConstant" => 5,
                ),
                array(
                    "group" => "remote",
                    "raw" => array(
                        3  => 1834,
                        4  => 4842,
                    ),
                    "converted" => false,
                    "id"  => 0,
                    "Date"   => 0,
                    "TestID" => null,
                    "deltaT"  => 1,
                    "Data0"  => 1,
                    "Data1"  => 2,
                    "Data2"  => 4,
                    "Data3"  => 8,
                    "Data4"  => 16,
                    "Data5"  => 32,
                    "Data6"  => null,
                    "Data7"  => null,
                    "Data8"  => null,
                    "Data9"  => null,
                    "Data10"  => null,
                    "Data11"  => null,
                    "Data12"  => null,
                    "Data13"  => null,
                    "Data14"  => null,
                ),
            ),
            array(
                array(
                    "id" => 21,
                    "Date" => 1234,
                    "deltaT" => 1,
                    0 => array(
                        "value" => 1,
                        "units" => "testUnit",
                        "unitType" => "firstUnit",
                        "dataType" => "raw",
                    ),
                    1 => array(
                        "value" => 2,
                        "units" => "testUnit",
                        "unitType" => "firstUnit",
                        "dataType" => "raw",
                    ),
                    2 => array(
                        "value" => 4,
                        "units" => "testUnit",
                        "unitType" => "firstUnit",
                        "dataType" => "raw",
                    ),
                    3 => array(
                        "value" => 8,
                        "units" => "testUnit",
                        "unitType" => "firstUnit",
                        "dataType" => "raw",
                    ),
                    4 => array(
                        "value" => 16,
                        "units" => "testUnit",
                        "unitType" => "firstUnit",
                        "dataType" => "raw",
                    ),
                    5 => array(
                        "value" => 32,
                        "units" => "testUnit",
                        "unitType" => "firstUnit",
                        "dataType" => "raw",
                    ),
                    "DataIndex" => 127,
                    "timeConstant" => 5,
                ),
                array(
                    "group" => "default",
                    "raw" => array(
                    ),
                    "converted" => false,
                    "id"  => 21,
                    "Date"   => 1234,
                    "TestID" => null,
                    "deltaT"  => 1,
                    "Data0"  => 1,
                    "Data1"  => 2,
                    "Data2"  => 4,
                    "Data3"  => 8,
                    "Data4"  => 16,
                    "Data5"  => 32,
                    "Data6"  => null,
                    "Data7"  => null,
                    "Data8"  => null,
                    "Data9"  => null,
                    "Data10"  => null,
                    "Data11"  => null,
                    "Data12"  => null,
                    "Data13"  => null,
                    "Data14"  => null,
                ),
            ),
            array(
                array(
                    "group" => "remote",
                    "deltaT" => 1,
                    "TestID" => 16,
                    0 => array(
                        "value" => 1,
                        "units" => "testUnit",
                        "unitType" => "firstUnit",
                        "dataType" => "raw",
                    ),
                    1 => array(
                        "value" => 2,
                        "units" => "testUnit",
                        "unitType" => "firstUnit",
                        "dataType" => "raw",
                    ),
                    2 => array(
                        "value" => 4,
                        "units" => "testUnit",
                        "unitType" => "firstUnit",
                        "dataType" => "raw",
                    ),
                    3 => array(
                        "value" => 8,
                        "units" => "testUnit",
                        "unitType" => "firstUnit",
                        "dataType" => "diff",
                        "raw" => 1834,
                    ),
                    4 => array(
                        "value" => 16,
                        "units" => "testUnit",
                        "unitType" => "firstUnit",
                        "dataType" => "diff",
                        "raw" => 4842,
                    ),
                    5 => array(
                        "value" => 32,
                        "units" => "testUnit",
                        "unitType" => "firstUnit",
                        "dataType" => "raw",
                    ),
                    "DataIndex" => 127,
                    "timeConstant" => 5,
                ),
                array(
                    "group" => "remote",
                    "raw" => array(
                        3  => 1834,
                        4  => 4842,
                    ),
                    "converted" => false,
                    "id"  => 0,
                    "Date"   => 0,
                    "TestID" => 16,
                    "deltaT"  => 1,
                    "Data0"  => 1,
                    "Data1"  => 2,
                    "Data2"  => 4,
                    "Data3"  => 8,
                    "Data4"  => 16,
                    "Data5"  => 32,
                    "Data6"  => null,
                    "Data7"  => null,
                    "Data8"  => null,
                    "Data9"  => null,
                    "Data10"  => null,
                    "Data11"  => null,
                    "Data12"  => null,
                    "Data13"  => null,
                    "Data14"  => null,
                ),
            ),
        );
    }

    /**
    * test the set routine when an extra class exists
    *
    * @param array $preload The value to preload
    * @param array $expect  The expected return
    *
    * @return null
    *
    * @dataProvider dataFromDataArray
    */
    public function testFromDataArray($preload, $expect)
    {
        $this->o->fromDataArray($preload);
        $this->assertSame($expect, $this->o->toArray());
    }
    /**
    * data provider for testDeviceID
    *
    * @return array
    */
    public static function dataFromAny()
    {
        return array(
            array(
                array(
                    "deltaT" => 1,
                    0 => array(
                        "value" => 1,
                        "units" => "testUnit",
                        "unitType" => "firstUnit",
                        "dataType" => "raw",
                    ),
                    1 => array(
                        "value" => 2,
                        "units" => "testUnit",
                        "unitType" => "firstUnit",
                        "dataType" => "raw",
                    ),
                    2 => array(
                        "value" => 4,
                        "units" => "testUnit",
                        "unitType" => "firstUnit",
                        "dataType" => "raw",
                    ),
                    3 => array(
                        "value" => 8,
                        "units" => "testUnit",
                        "unitType" => "firstUnit",
                        "dataType" => "raw",
                    ),
                    4 => array(
                        "value" => 16,
                        "units" => "testUnit",
                        "unitType" => "firstUnit",
                        "dataType" => "raw",
                    ),
                    5 => array(
                        "value" => 32,
                        "units" => "testUnit",
                        "unitType" => "firstUnit",
                        "dataType" => "raw",
                    ),
                    "DataIndex" => 127,
                    "timeConstant" => 5,
                ),
                array(
                    "group" => "default",
                    "raw" => array(),
                    "converted" => false,
                    "id"  => 0,
                    "Date"   => 0,
                    "TestID" => null,
                    "deltaT"  => 1,
                    "Data0"  => 1,
                    "Data1"  => 2,
                    "Data2"  => 4,
                    "Data3"  => 8,
                    "Data4"  => 16,
                    "Data5"  => 32,
                    "Data6"  => null,
                    "Data7"  => null,
                    "Data8"  => null,
                    "Data9"  => null,
                    "Data10"  => null,
                    "Data11"  => null,
                    "Data12"  => null,
                    "Data13"  => null,
                    "Data14"  => null,
                ),
            ),
            array(
                array(
                    "id"  => 41,
                    "Date"   => "2003-02-28 01:59:00",
                    "deltaT"  => 5.2,
                    "Data0"  => 0,
                    "Data1"  => 1,
                    "Data2"  => 2,
                    "Data3"  => 3,
                    "Data4"  => 4,
                    "Data5"  => 5,
                    "Data6"  => 6,
                    "Data7"  => 7,
                    "Data8"  => 8,
                    "Data9"  => 9,
                    "Data10"  => 10,
                    "Data11"  => 11,
                    "Data12"  => 12,
                    "Data13"  => 13,
                    "Data14"  => 14,
                ),
                array(
                    "group" => "default",
                    "raw" => array(),
                    "converted" => false,
                    "id"  => 41,
                    "Date"   => 1046397540,
                    "TestID" => null,
                    "deltaT"  => 5.2,
                    "Data0"  => 0,
                    "Data1"  => 1,
                    "Data2"  => 2,
                    "Data3"  => 3,
                    "Data4"  => 4,
                    "Data5"  => 5,
                    "Data6"  => 6,
                    "Data7"  => 7,
                    "Data8"  => 8,
                    "Data9"  => 9,
                    "Data10"  => 10,
                    "Data11"  => 11,
                    "Data12"  => 12,
                    "Data13"  => 13,
                    "Data14"  => 14,
                ),
            ),
        );
    }

    /**
    * test the set routine when an extra class exists
    *
    * @param array $preload The value to preload
    * @param array $expect  The expected return
    *
    * @return null
    *
    * @dataProvider dataFromAny
    */
    public function testFromAny($preload, $expect)
    {
        $this->o->fromAny($preload);
        $this->assertAttributeSame($expect, "data", $this->o);
    }
    /**
    * data provider for testSet
    *
    * @return array
    */
    public static function dataSet()
    {
        return array(
            array("Date", "2010-04-25 13:42:23", 1272202943),
            array("Date", "2010-04-25", 1272153600),
            array("Date", "Sun, 25 April 2010, 1:42:23pm", 1272202943),
            array("Date", 1234567890, 1234567890),
            array("Date", "This is not a date", 0),
        );
    }

    /**
    * test the set routine when an extra class exists
    *
    * @param string $var    The variable to set
    * @param mixed  $value  The value to set
    * @param mixed  $expect The expected return
    *
    * @return null
    *
    * @dataProvider dataSet
    */
    public function testSet($var, $value, $expect)
    {
        $this->o->set($var, $value);
        $data = $this->readAttribute($this->o, "data");
        $this->assertSame($expect, $data[$var]);
    }
    /**
    * Data provider for testGetPeriod
    *
    * @return array
    */
    public static function dataGetPeriod()
    {
        return array(
            array(
                array(
                ),
                1292648500,
                1292648601,
                2,
                array(
                    array(
                        "group" => "default",
                        "raw" => array(),
                        "converted" => false,
                        "id"  => 2,
                        "Date"   => 1292648600,
                        "TestID" => null,
                        "deltaT"  => "1.3",
                        "Data0"  => "1.0",
                        "Data1"  => "2.0",
                        "Data2"  => "3.0",
                        "Data3"  => "4.0",
                        "Data4"  => "5.0",
                        "Data5"  => "6.0",
                        "Data6"  => "7.0",
                        "Data7"  => "8.0",
                        "Data8"  => "9.0",
                        "Data9"  => "10.0",
                        "Data10"  => "11.0",
                        "Data11"  => "12.0",
                        "Data12"  => "13.0",
                        "Data13"  => "14.0",
                        "Data14"  => "15.0",
                    ),
                    array(
                        "group" => "default",
                        "raw" => array(),
                        "converted" => false,
                        "id"  => 2,
                        "Date"   => 1292648500,
                        "TestID" => null,
                        "deltaT"  => "1.3",
                        "Data0"  => "1.0",
                        "Data1"  => "2.0",
                        "Data2"  => "3.0",
                        "Data3"  => "4.0",
                        "Data4"  => "5.0",
                        "Data5"  => "6.0",
                        "Data6"  => "7.0",
                        "Data7"  => "8.0",
                        "Data8"  => "9.0",
                        "Data9"  => "10.0",
                        "Data10"  => "11.0",
                        "Data11"  => "12.0",
                        "Data12"  => "13.0",
                        "Data13"  => "14.0",
                        "Data14"  => "15.0",
                    ),
                ),
            ),
        );
    }
    /**
    * Tests for verbosity
    *
    * @param array $preload The array to preload into the class
    * @param int   $start   The first date
    * @param int   $end     The last date
    * @param mixed $key     The key to use
    * @param array $expect  The expected return
    *
    * @dataProvider dataGetPeriod
    *
    * @return null
    */
    public function testGetPeriod($preload, $start, $end, $key, $expect)
    {
        $ret = $this->o->getPeriod($start, $end, $key);
        if ($ret !== false) {
            $ret = array();
            do {
                $ret[] = $this->o->toArray();
            } while ($this->o->nextInto());
        }
        $this->assertSame($expect, $ret);
    }
    /**
    * Data provider for testExists
    *
    * @return array
    */
    public static function dataExists()
    {
        return array(
            array(
                array(
                    "id" => 2,
                    "Date" => 1292648500
                ),
                null,
                true,
            ),
            array(
                array(
                    "id" => 2,
                    "Date" => 1292648499
                ),
                null,
                false,
            ),
            array(
                array(
                    "id" => 2,
                    "Date" => 1292648450
                ),
                120,
                true,
            ),
            array(
                array(
                    "id" => 2,
                    "Date" => 1292648450
                ),
                60,
                false,
            ),
        );
    }
    /**
    * Tests for verbosity
    *
    * @param array $preload The array to preload into the class
    * @param int   $period  The period to search for a duplicate
    * @param array $expect  The expected return
    *
    * @dataProvider dataExists
    *
    * @return null
    */
    public function testExists($preload, $period, $expect)
    {
        $this->o->fromAny($preload);
        $ret = $this->o->exists($period);
        $this->assertSame($expect, $ret);
    }
}

namespace HUGnet\db\tables;
/**
 * Test class for HUGnetDB.
 * Generated by PHPUnit on 2007-12-13 at 10:28:11.
 *
 * @category   Libraries
 * @package    HUGnetLibTest
 * @subpackage SuiteTables
 * @author     Scott Price <prices@hugllc.com>
 * @copyright  2014 Hunt Utilities Group, LLC
 * @license    http://opensource.org/licenses/gpl-license.php GNU Public License
 * @link       http://dev.hugllc.com/index.php/Project:HUGnetLib
 */
class HistoryTestStub extends \HUGnet\db\History
    implements \HUGnet\interfaces\DBTable
{
    /** @var string This is the table we should use */
    public $sqlTable = "History";
}
?>
