<?php
/**
 * Tests the filter class
 *
 * PHP Version 5
 *
 * <pre>
 * HUGnetLib is a library of HUGnet code
 * Copyright (C) 2007-2010 Hunt Utilities Group, LLC
 * Copyright (C) 2009 Scott Price
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 * </pre>
 *
 * @category   Test
 * @package    HUGnetLibTest
 * @subpackage Tables
 * @author     Scott Price <prices@hugllc.com>
 * @copyright  2007-2010 Hunt Utilities Group, LLC
 * @copyright  2009 Scott Price
 * @license    http://opensource.org/licenses/gpl-license.php GNU Public License
 * @version    SVN: $Id$
 * @link       https://dev.hugllc.com/index.php/Project:HUGnetLib
 *
 */


require_once dirname(__FILE__).'/../../tables/RawHistoryTable.php';
require_once dirname(__FILE__)."/HUGnetDBTableTestBase.php";

/**
 * Test class for filter.
 * Generated by PHPUnit_Util_Skeleton on 2007-10-30 at 08:44:56.
 *
 * @category   Test
 * @package    HUGnetLibTest
 * @subpackage Tables
 * @author     Scott Price <prices@hugllc.com>
 * @copyright  2007-2010 Hunt Utilities Group, LLC
 * @copyright  2009 Scott Price
 * @license    http://opensource.org/licenses/gpl-license.php GNU Public License
 * @link       https://dev.hugllc.com/index.php/Project:HUGnetLib
 */
class RawHistoryTableTest extends HUGnetDBTableTestBase
{

    /**
    * Sets up the fixture, for example, open a network connection.
    * This method is called before a test is executed.
    *
    * @return null
    *
    * @access protected
    */
    protected function setUp()
    {
        $config = array(
        );
        $this->config = &ConfigContainer::singleton();
        $this->config->forceConfig($config);
        $this->pdo = &$this->config->servers->getPDO();
        $this->o = new RawHistoryTable();
        $this->o->create();
        parent::Setup();
    }

    /**
    * Tears down the fixture, for example, close a network connection.
    * This method is called after a test is executed.
    *
    * @return null
    *
    * @access protected
    */
    protected function tearDown()
    {
        $this->o = null;
        $this->config = null;
    }
    /**
    * This gets us our database preload
    *
    * @access protected
    *
    * @return null
    */
    protected function getDataSet()
    {
        return $this->createXMLDataSet(
            dirname(__FILE__).'/../files/RawHistoryTableTest.xml'
        );
    }
    /**
    * data provider for testDeviceID
    *
    * @return array
    */
    public static function dataColumns()
    {
        $o = new RawHistoryTable();
        return HUGnetDBTableTestBase::splitObject($o, "sqlColumns");
    }
    /**
    * data provider for testDeviceID
    *
    * @return array
    */
    public static function dataIndexes()
    {
        $o = new RawHistoryTable();
        return HUGnetDBTableTestBase::splitObject($o, "sqlIndexes");
    }
    /**
    * data provider for testDeviceID
    *
    * @return array
    */
    public static function dataVars()
    {
        return array(
            array(new RawHistoryTable()),
        );
    }

    /**
    * data provider for testDeviceID
    *
    * @return array
    */
    public static function dataFromArray()
    {
        return array(
            array(
                array(
                    "id" => 100,
                    "packet" => array(
                        "To" => "000012",
                        "From" => "000283",
                        "Date" => 1048472484,
                        "Command" => "55",
                        "Data" => "01020304",
                    ),
                    "device" => new DeviceContainer(),
                    "command" => "55",
                    "dataIndex" => 123,
                ),
                array(
                    "group" => "default",
                    "id" => 100,
                    "Date" => 0,
                    "packet" => array(
                        "To" => "000012",
                        "From" => "000283",
                        "Date" => 1048472484,
                        "Command" => "55",
                        "Length" => 4,
                        "Time" => 0.0,
                        "Data" => array(1,2,3,4),
                        "RawData" => "01020304",
                        "Type" => "SENSORREAD",
                        "Reply" => null,
                        "Checksum" => "C6",
                        "CalcChecksum" => "C6",
                    ),
                    "command" => "55",
                    "dataIndex" => 123,
                ),
            ),
            array(
                array(
                    "id" => 100,
                    "packet" => array(
                        "To" => "000012",
                        "From" => "000283",
                        "Date" => 1048472484,
                        "Command" => "55",
                        "Data" => "01020304",
                    ),
                    "device" => array(),
                    "command" => "55",
                    "dataIndex" => 123,
                ),
                array(
                    "group" => "default",
                    "id" => 100,
                    "Date" => 0,
                    "packet" => array(
                        "To" => "000012",
                        "From" => "000283",
                        "Date" => 1048472484,
                        "Command" => "55",
                        "Length" => 4,
                        "Time" => 0.0,
                        "Data" => array(1,2,3,4),
                        "RawData" => "01020304",
                        "Type" => "SENSORREAD",
                        "Reply" => null,
                        "Checksum" => "C6",
                        "CalcChecksum" => "C6",
                    ),
                    "command" => "55",
                    "dataIndex" => 123,
                ),
            ),
        );
    }

    /**
    * test the set routine when an extra class exists
    *
    * @param array $preload The value to preload
    * @param array $expect  The expected return
    *
    * @return null
    *
    * @dataProvider dataFromArray
    */
    public function testFromArray($preload, $expect)
    {
        $date = time();
        $this->o->fromArray($preload);
        $data = $this->readAttribute($this->o, "data");
        $this->assertSame("PacketContainer", get_class($this->o->packet));
        $row = $this->o->toArray();
        $this->assertThat(
            $row["devicesHistoryDate"],
            $this->greaterThanOrEqual($date),
            "Date is wrong on key $key"
        );
        unset($row["devicesHistoryDate"]);
        $this->assertSame($expect, $row);
    }
    /**
    * data provider for testSet
    *
    * @return array
    */
    public static function dataSet()
    {
        return array(
            array("Date", "2010-04-25 13:42:23", 1272202943),
            array("Date", "2010-04-25", 1272153600),
            array("Date", "Sun, 25 April 2010, 1:42:23pm", 1272202943),
            array("Date", 1234567890, 1234567890),
            array("Date", "This is not a date", 0),
            array("id", 71, 71),
        );
    }

    /**
    * test the set routine when an extra class exists
    *
    * @param string $var    The variable to set
    * @param mixed  $value  The value to set
    * @param mixed  $expect The expected return
    *
    * @return null
    *
    * @dataProvider dataSet
    */
    public function testSet($var, $value, $expect)
    {
        $this->o->$var = $value;
        $data = $this->readAttribute($this->o, "data");
        $this->assertSame($expect, $data[$var]);
    }
    /**
    * Data provider for testInsertRow
    *
    * @return array
    */
    public static function dataInsertRecord()
    {
        $packet = new PacketContainer(
            array(
                "Date" => "2003-01-23 23:35:12",
            )
        );
        $device = new DeviceContainer();

        return array(
            array(
                array(
                        "id"        => "123",
                        "Date"      => "1977-01-01 08:09:00",
                        "packet"    => $packet->toString(),
                        "device"    => $device->toArray(),
                        "command"   => "55",
                        "dataIndex" => "232",
                ),
                array(
                    array(
                        "id"        => "123",
                        "Date"      => "220954140",
                        "packet"    => $packet->toZip(),
                        "command"   => "55",
                        "dataIndex" => "232",
                    ),
                ),
            ),
        );
    }
    /**
    * Tests for verbosity
    *
    * @param array $preload The array to preload into the class
    * @param array $expect  The expected return
    *
    * @dataProvider dataInsertRecord
    *
    * @return null
    */
    public function testInsertRecord($preload, $expect)
    {
        $date = time();
        RawHistoryTable::insertRecord($preload);
        $stmt = $this->pdo->query("SELECT * FROM `rawHistory`");
        $rows = $stmt->fetchAll(PDO::FETCH_ASSOC);
        foreach (array_keys($rows) as $key) {
            $this->assertThat(
                $rows[$key]["devicesHistoryDate"],
                $this->greaterThanOrEqual($date),
                "Date is wrong on key $key"
            );
            unset($rows[$key]["devicesHistoryDate"]);
        }
        $this->assertSame($expect, $rows);
    }
    /**
    * Data provider for testGetDevice
    *
    * @return array
    */
    public static function dataGetDevice()
    {
        return array(
            array(
                array(
                    "id" => 18,
                    "Date" => 1048472484,
                    "packet" => array(
                        "To" => "000012",
                        "From" => "000283",
                        "Date" => 1048472484,
                        "Command" => "55",
                        "Data" => "",
                        "Reply" => array(
                            "To" => "000283",
                            "From" => "000012",
                            "Date" => 1048472485,
                            "Command" => "01",
                            "Data" => "01020304050607080910",
                        ),
                    ),
                    "device" => array(
                        "id" => 18,
                        "DeviceID" => "000012",
                        "HWPartNum" => "0039-21-02-A",
                        "FWPartNum" => "0039-20-14-C",
                        "FWVerson" => "0.1.2",
                    ),
                    "command" => "55",
                    "dataIndex" => 123,
                ),
                array(
                    'DriverInfo' => array(
                        'TimeConstant' => 1,
                        'NumSensors' => 6,
                    ),
                    'id' => 18,
                    'DeviceID' => '000012',
                    'HWPartNum' => '0039-21-02-A',
                    'FWPartNum' => '0039-20-14-C',
                    'FWVersion' => '0.0.0',
                    'RawSetup' => '000000001200392102410039201443000000FFFFFF00',
                    'Driver' => 'e00392100',
                    'sensors' => array(
                        'Sensors' => 6,
                        0 => array(
                            'id' => 64,
                            'type' => 'Controller',
                            'location' => 'HUGnet 1 Voltage',
                            'extra' => array(
                                0 => 180,
                                1 => 27,
                            ),
                        ),
                        1 => array(
                            'id' => 80,
                            'type' => 'Controller',
                            'location' => 'HUGnet 1 Current',
                            'extra' => array(
                                0 => 0.5,
                                1 => 7,
                            ),
                        ),
                        2 => array(
                            'id' => 2,
                            'type' => 'BCTherm2322640',
                            'location' => 'HUGnet 1 FET Temperature',
                            'extra' => array(
                                0 => 100,
                                1 => 10,
                            ),
                        ),
                        3 => array(
                            'id' => 64,
                            'type' => 'Controller',
                            'location' => 'HUGnet 2 Voltage',
                            'extra' => array(
                                0 => 180,
                                1 => 27,
                            ),
                        ),
                        4 => array(
                            'id' => 80,
                            'type' => 'Controller',
                            'location' => 'HUGnet 2 Current',
                            'extra' => array(
                                0 => 0.5,
                                1 => 7,
                            ),
                        ),
                        5 => array(
                            'id' => 2,
                            'type' => 'BCTherm2322640',
                            'location' => 'HUGnet 2 FET Temperature',
                            'extra' => array(
                                0 => 100,
                                1 => 10,
                            ),
                        ),
                    ),
                    'params' => array(
                        'DriverInfo' => array(
                            'BoredomThreshold' => 0,
                        ),
                    ),
                ),
            ),
        );
    }
    /**
    * Tests for verbosity
    *
    * @param array $preload The array to preload into the class
    * @param array $expect  The expected return
    *
    * @dataProvider dataGetDevice
    *
    * @return null
    */
    public function testGetDevice($preload, $expect)
    {
        $this->o->clearData();
        $this->o->fromAny($preload);
        $array = $this->o->getDevice()->toArray(false);
        $this->assertSame($expect, $array);
    }
    /**
    * Data provider for testToHistory
    *
    * @return array
    */
    public static function dataToHistoryTable()
    {
        return array(
            array(
                array(),
                array(
                    "id" => 18,
                    "Date" => 1048472484,
                    "packet" => array(
                        "To" => "000012",
                        "From" => "000283",
                        "Date" => 1048472484,
                        "Command" => "55",
                        "Data" => "",
                        "Reply" => array(
                            "To" => "000283",
                            "From" => "000012",
                            "Date" => 1048472485,
                            "Command" => "01",
                            "Data" => "631902BA100200B947124902008F0FA103",
                        ),
                    ),
                    "device" => array(
                        "id" => 18,
                        "DeviceID" => "000012",
                        "HWPartNum" => "0039-21-02-A",
                        "FWPartNum" => "0039-20-14-C",
                        "FWVerson" => "0.1.2",
                    ),
                    "command" => "55",
                    "dataIndex" => 123,
                ),
                1048472184,
                array(),
                array(
                    "id" => 18,
                    "Date" => 1048472484,
                    'deltaT' => 300,
                    'Data0' => 10.749,
                    'Data1' => 11.7,
                    'Data2' => 33.3514,
                    'Data3' => 10.951,
                    'Data4' => 20.3,
                    'Data5' => 35.2126,
                ),
            ),
            array(
                array(),
                array(
                    "id" => 18,
                    "Date" => 1048472484,
                    "packet" => array(
                        "To" => "000012",
                        "From" => "000283",
                        "Date" => 1048472484,
                        "Command" => "55",
                        "Data" => "",
                    ),
                    "device" => array(
                        "id" => 18,
                        "DeviceID" => "000012",
                        "HWPartNum" => "0039-21-02-A",
                        "FWPartNum" => "0039-20-14-C",
                        "FWVerson" => "0.1.2",
                    ),
                    "command" => "55",
                    "dataIndex" => 123,
                ),
                1048472184,
                array(),
                array(
                ),
            ),
            array(
                array(),
                array(
                    "id" => 18,
                    "Date" => 1048472484,
                    "packet" => array(
                        "To" => "000012",
                        "From" => "000283",
                        "Date" => 1048472484,
                        "Command" => "55",
                        "Data" => "",
                        "Reply" => array(
                            "To" => "000283",
                            "From" => "000012",
                            "Date" => 1048472485,
                            "Command" => "01",
                            "Data" => "C80001A013006813003213006913003A140083130102"
                                ."025D029200BF00EC",
                        ),
                    ),
                    "device" => array(
                        "id" => 18,
                        "DeviceID" => "000012",
                        "HWPartNum" => "0039-12-01-A",
                        "FWPartNum" => "0039-20-03-C",
                        "FWVerson" => "0.1.2",
                        "sensors" => array(
                            "Sensors" => 5,
                            0 => array(),
                            1 => array(),
                            2 => array("dataType" => UnitsBase::TYPE_DIFF),
                            3 => array("dataType" => UnitsBase::TYPE_DIFF),
                            4 => array(),
                        ),
                    ),
                    "command" => "55",
                    "dataIndex" => 123,
                ),
                1048472184,
                array(null, null, 91.4234, 90.5231, null),
                array(
                    "id" => 18,
                    "raw" => array(
                        2 => 93.9263,
                        3 => 93.5304,
                    ),
                    "Date" => 1048472484,
                    'deltaT' => 300,
                    'Data0' => 93.1399,
                    'Data1' => 93.5384,
                    'Data2' => 2.5029,
                    'Data3' => 3.0073,
                    'Data4' => 92.0645,
                ),
            ),
            array(
                array(
                    array(
                        "id" => 18,
                        "Date" => 1048472184,
                        "packet" => array(
                            "To" => "000012",
                            "From" => "000283",
                            "Date" => 1048472184,
                            "Command" => "55",
                            "Data" => "",
                            "Reply" => array(
                                "To" => "000283",
                                "From" => "000012",
                                "Date" => 1048472185,
                                "Command" => "01",
                                "Data" => "C80001A013006813001614006914003A14008313"
                                    ."0102025D029200BF00EC",
                            ),
                        ),
                        "device" => array(
                            "id" => 18,
                            "DeviceID" => "000012",
                            "HWPartNum" => "0039-12-01-A",
                            "FWPartNum" => "0039-20-03-C",
                            "FWVerson" => "0.1.2",
                            "sensors" => array(
                                "Sensors" => 5,
                                0 => array(),
                                1 => array(),
                                2 => array("dataType" => UnitsBase::TYPE_DIFF),
                                3 => array("dataType" => UnitsBase::TYPE_DIFF),
                                4 => array(),
                            ),
                        ),
                        "command" => "55",
                        "dataIndex" => 123,
                    ),
                    array(
                        "id" => 18,
                        "Date" => 1048472084,
                        "packet" => array(
                            "To" => "000012",
                            "From" => "000283",
                            "Date" => 1048472084,
                            "Command" => "55",
                            "Data" => "",
                            "Reply" => array(
                                "To" => "000283",
                                "From" => "000012",
                                "Date" => 1048472085,
                                "Command" => "01",
                                "Data" => "C80001A013006813001612006912003A14008313"
                                    ."0102025D029200BF00EC",
                            ),
                        ),
                        "device" => array(
                            "id" => 18,
                            "DeviceID" => "000012",
                            "HWPartNum" => "0039-12-01-A",
                            "FWPartNum" => "0039-20-03-C",
                            "FWVerson" => "0.1.2",
                            "sensors" => array(
                                "Sensors" => 5,
                                0 => array(),
                                1 => array(),
                                2 => array("dataType" => UnitsBase::TYPE_DIFF),
                                3 => array("dataType" => UnitsBase::TYPE_DIFF),
                                4 => array(),
                            ),
                        ),
                        "command" => "55",
                        "dataIndex" => 123,
                    ),
                ),
                array(
                    "id" => 18,
                    "Date" => 1048472484,
                    "packet" => array(
                        "To" => "000012",
                        "From" => "000283",
                        "Date" => 1048472484,
                        "Command" => "55",
                        "Data" => "",
                        "Reply" => array(
                            "To" => "000283",
                            "From" => "000012",
                            "Date" => 1048472485,
                            "Command" => "01",
                            "Data" => "C80001A013006813003213006913003A140083130102"
                                ."025D029200BF00EC",
                        ),
                    ),
                    "device" => array(
                        "id" => 18,
                        "DeviceID" => "000012",
                        "HWPartNum" => "0039-12-01-A",
                        "FWPartNum" => "0039-20-03-C",
                        "FWVerson" => "0.1.2",
                        "sensors" => array(
                            "Sensors" => 5,
                            0 => array(),
                            1 => array(),
                            2 => array("dataType" => UnitsBase::TYPE_DIFF),
                            3 => array("dataType" => UnitsBase::TYPE_DIFF),
                            4 => array(),
                        ),
                    ),
                    "command" => "55",
                    "dataIndex" => 123,
                ),
                0,
                array(),
                array(
                    "id" => 18,
                    "raw" => array(
                        2 => 93.9263,
                        3 => 93.5304,
                    ),
                    "Date" => 1048472484,
                    'deltaT' => 300,
                    'Data0' => 93.1399,
                    'Data1' => 93.5384,
                    'Data2' => 1.6131,
                    'Data3' => 1.7878,
                    'Data4' => 92.0645,
                ),
            ),
        );
    }
    /**
    * Tests for verbosity
    *
    * @param array $preload The array to preload into the class
    * @param array $time    The time of the last packet
    * @param array $expect  The expected return
    *
    * @dataProvider dataToHistoryTable
    *
    * @return null
    */
    public function testToHistoryTable($db, $preload, $time, $prev, $expect)
    {
        foreach ($db as $p) {
            $this->o->clearData();
            $this->o->fromAny($p);
            $this->o->insertRow();
        }
        $this->o->clearData();
        $this->o->fromAny($preload);
        $array = $this->o->toHistoryTable($time, $prev)->toArray(false);
        $this->assertEquals($expect, $array, "", 0.1);
    }

}

?>
