<?php
/**
 * Tests the filter class
 *
 * PHP Version 5
 *
 * <pre>
 * HUGnetLib is a library of HUGnet code
 * Copyright (C) 2007-2011 Hunt Utilities Group, LLC
 * Copyright (C) 2009 Scott Price
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 * </pre>
 *
 * @category   Libraries
 * @package    HUGnetLibTest
 * @subpackage SuitePlugins
 * @author     Scott Price <prices@hugllc.com>
 * @copyright  2007-2011 Hunt Utilities Group, LLC
 * @copyright  2009 Scott Price
 * @license    http://opensource.org/licenses/gpl-license.php GNU Public License
 * @version    SVN: $Id$
 * @link       https://dev.hugllc.com/index.php/Project:HUGnetLib
 *
 */

/** Get our classes */
require_once CODE_BASE.'plugins/virtualSensors/PhysicalPointVirtualSensor.php';
/** This is a required class */
require_once TEST_CONFIG_BASE.'stubs/DummyDeviceContainer.php';
/** This is a required class */
require_once 'VirtualSensorPluginTestBase.php';

/**
 * Test class for filter.
 * Generated by PHPUnit_Util_Skeleton on 2007-10-30 at 08:44:56.
 *
 * @category   Libraries
 * @package    HUGnetLibTest
 * @subpackage SuitePlugins
 * @author     Scott Price <prices@hugllc.com>
 * @copyright  2007-2011 Hunt Utilities Group, LLC
 * @copyright  2009 Scott Price
 * @license    http://opensource.org/licenses/gpl-license.php GNU Public License
 * @link       https://dev.hugllc.com/index.php/Project:HUGnetLib
 *
 * @SuppressWarnings(PHPMD.ShortVariable)
 */
class PhysicalPointVirtualSensorTest extends VirtualSensorPluginTestBase
{

    /**
    * Sets up the fixture, for example, open a network connection.
    * This method is called before a test is executed.
    *
    * @return null
    *
    * @access protected
    */
    protected function setUp()
    {
        $config = array(
        );
        $this->config = &ConfigContainer::singleton();
        $this->config->forceConfig($config);
        $this->socket = &$this->config->sockets->getSocket("default");
        $this->d = new DeviceContainer();
        $this->o = new PhysicalPointVirtualSensor(
            array(
            ),
            $this->d
        );
    }

    /**
    * Tears down the fixture, for example, close a network connection.
    * This method is called after a test is executed.
    *
    * @return null
    *
    * @access protected
    */
    protected function tearDown()
    {
        unset($this->o);
    }

    /**
    * Data provider for testRegisterPlugin
    *
    * @return array
    */
    public static function dataRegisterPlugin()
    {
        return array(
            array("PhysicalPointVirtualSensor"),
        );
    }
    /**
    * data provider for testSet
    *
    * @return array
    */
    public static function dataSet()
    {
        return array(
            array("location", "raw", "raw"),
        );
    }
    /**
    * Data provider for testConstructor
    *
    * @return array
    */
    public static function dataConstructor()
    {
        return array(
            array(
                array(
                    "DeviceID" => "0000E1",
                    "sensors" => array(
                        "Sensors" => 4,
                        "forceSensors" => true,
                        "PhysicalSensors" => 3,
                        "VirtualSensors" => 1,
                        0 => array(),
                        1 => array(),
                        2 => array(
                            "id" => 0x02,
                            "location" => "Hello",
                            "dataType" => UnitsBase::TYPE_DIFF,
                        ),
                    ),
                ),
                array(
                    'extra' => array(
                        "0000E1", 3
                    )
                ),
                array(
                    "id" => 0xFE,
                    "type" => "physicalpoint",
                    "location" => "Hello",
                    "dataType" => UnitsBase::TYPE_DIFF,
                    'extra' => array(
                        "0000E1", 3
                    ),
                    "units" => '&#176;F',
                    "bound" => false,
                    "rawCalibration" => "",
                    "decimals" => 2,
                    "filter" => array(),
                    'doppelganger' => 1,
                ),
                array(
                    'longName' => 'PhysicalPoint Virtual Sensor',
                    'unitType' => 'Temperature',
                    'extraValues' => array (
                        0 => 8,
                        1 => 4,
                    ),
                    'extraText' => array (
                        0 => 'Device ID',
                        1 => 'Sensor',
                    ),
                    'extraDefault' => array (
                        0 => '',
                        1 => 1,
                    ),
                    'storageType' => UnitsBase::TYPE_RAW,
                    'storageUnit' => '&#176;C',
                    'maxDecimals' => 2,
                    'doppelganger' => true,
                ),
                array(
                    'id' => 254,
                    'type' => 'physicalpoint',
                    'location' => 'Hello',
                    'dataType' => UnitsBase::TYPE_DIFF,
                    'extra' => array (
                    ),
                    'units' => '&#176;F',
                    'bound' => false,
                    'rawCalibration' => '',
                    'decimals' => 2,
                    'filter' => array(),
               ),
            ),
        );
    }
    /**
    * Generic function for testing sensor routines
    *
    * This is called by using parent::sensorTest()
    *
    * @param array $device  The device to load
    * @param array $preload The data to preload into the class
    * @param mixed $expect  The return data to expect
    * @param mixed $fixed   The fixed data to expect
    * @param mixed $default The default data to expect
    *
    * @return null
    *
    * @dataProvider dataConstructor()
    */
    public function testConstructor($device, $preload, $expect, $fixed, $default)
    {
        $dev = new DeviceContainer();
        $dev->fromAny($device);
        $dev->insertRow(true);
        $o = new PhysicalPointVirtualSensor($preload, $this->d);
        $this->assertSame($expect, $o->toArray(true), "Array output wrong");
        $this->assertAttributeSame(
            $fixed, "fixed", $o, "Fixed is wrong"
        );
        $this->assertAttributeSame(
            $default, "default", $o, "Default is wrong"
        );
    }
    /**
    * Data provider for testGetReading
    *
    * @return array
    */
    public static function dataGetReading()
    {
        return array(
            array( // #0 Nothing
                array(
                    "extra" => array(
                        "0000E1",
                        2,
                    ),
                ),
                0,
                0,
                array(
                ),
                null
            ),
            array( // #0 Nothing
                array(
                    "extra" => array(
                        "0000E1",
                        2,
                    ),
                ),
                0,
                0,
                array(
                    "Data1" => 15,
                ),
                15,
            ),
        );
    }
    /**
    * Generic function for testing sensor routines
    *
    * This is called by using parent::sensorTest()
    *
    * @param array $preload The data to preload into the class
    * @param int   $A       Output of the A to D converter
    * @param float $deltaT  The time delta in seconds between this record
    * @param mixed $data    The data for the sensor to work with
    * @param mixed $expect  The return data to expect
    *
    * @return null
    *
    * @dataProvider dataGetReading()
    */
    public function testGetReading($preload, $A, $deltaT, $data, $expect)
    {

        $o = new PhysicalPointVirtualSensor($preload, $this->d);
        $ret = $o->getReading($A, $deltaT, $data);
        $this->assertSame($expect, $ret);
    }

    /**
    * Data provider for testGetReading
    *
    * @return array
    */
    public static function dataGetAverageTable()
    {
        return array(
            array( // #0 Nothing
                array(
                    "id" => 0xE1,
                    "DeviceID" => "0000E1",
                    "HWPartNum" => "0039-28-01-A",
                    "Driver" => "e00392800",
                ),
                array(
                    "extra" => array(
                        "0000E1",
                        2,
                    ),
                ),
                "E00392800AverageTable",
                0xE1,
            ),
        );
    }
    /**
    * Generic function for testing sensor routines
    *
    * @param array  $device  The device to load
    * @param array  $preload The data to preload into the class
    * @param string $class   The class returned
    * @param int    $id      The ID of the device we expect
    *
    * @return null
    *
    * @dataProvider dataGetAverageTable
    */
    public function testGetAverageTable($device, $preload, $class, $id)
    {
        $dev = new DeviceContainer();
        $dev->fromAny($device);
        $dev->insertRow(true);

        $o = new PhysicalPointVirtualSensor($preload, $this->d);
        $ret = &$o->getAverageTable();
        $this->assertSame($class, get_class($ret), "Class Wrong");
        $this->assertAttributeSame($id, "DeviceID", $o, "Id Wrong");
    }

}

?>
