<?php
/**
 * This runs all of the tests associated with HUGnetLib.
 *
 * PHP Version 5
 *
 * <pre>
 * HUGnetLib is a library of HUGnet code
 * Copyright (C) 2013 Hunt Utilities Group, LLC
 * Copyright (C) 2009 Scott Price
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 * </pre>
 *
 * @category   Libraries
 * @package    HUGnetLibTest
 * @subpackage SuiteBase
 * @author     Scott Price <prices@hugllc.com>
 * @copyright  2013 Hunt Utilities Group, LLC
 * @copyright  2009 Scott Price
 * @license    http://opensource.org/licenses/gpl-license.php GNU Public License
 * @link       http://dev.hugllc.com/index.php/Project:HUGnetLib
 */
/** This is the HUGnet namespace */
namespace HUGnet\devices;
/** This is a required class */
require_once CODE_BASE.'devices/Properties.php';
/** This is a required class */
require_once CODE_BASE.'system/System.php';
/** This is a required class */
require_once TEST_CONFIG_BASE.'stubs/DummyTable.php';
/** This is a required class */
require_once TEST_CONFIG_BASE.'stubs/DummySystem.php';
/** This is our interface */
require_once CODE_BASE.'devices/drivers/DriverInterface.php';

/**
 * Test class for HUGnetDB.
 * Generated by PHPUnit on 2007-12-13 at 10:28:11.
 *
 * @category   Libraries
 * @package    HUGnetLibTest
 * @subpackage SuiteBase
 * @author     Scott Price <prices@hugllc.com>
 * @copyright  2013 Hunt Utilities Group, LLC
 * @copyright  2009 Scott Price
 * @license    http://opensource.org/licenses/gpl-license.php GNU Public License
 * @version    Release: 0.10.2
 * @link       http://dev.hugllc.com/index.php/Project:HUGnetLib
 */
class PropertiesTest extends \PHPUnit_Framework_TestCase
{
    /** test object */
    protected $o;


    /**
    * Sets up the fixture, for example, opens a network connection.
    * This method is called before a test is executed.
    *
    * @access protected
    *
    * @return null
    */
    protected function setUp()
    {
        $this->o = Properties::factory(TEST_CONFIG_BASE."/files/devices.xml");
    }

    /**
    * Tears down the fixture, for example, closes a network connection.
    * This method is called after a test is executed.
    *
    * @access protected
    *
    * @return null
    */
    protected function tearDown()
    {
        unset($this->o);
    }

    /**
    * data provider for testDeviceID
    *
    * @return array
    */
    public static function dataGetEndpoints()
    {
        return array(
            array(
                true,
                array(
                    0 => '0039-12-01-A',
                    1 => '0039-12-02-A',
                    2 => '0039-12-02-B',
                    3 => '0039-12-02-C',
                    4 => '0039-21-01-A',
                    5 => '0039-21-02-A',
                    6 => '0039-28-01-A',
                    7 => '0039-37-01-A',
                    8 => '0039-37-01-B',
                    9 => '0039-37-01-C',
                    10 => '0039-37-01-D',
                    11 => '0039-37-01-E',
                    12 => '0039-37-01-F',
                    13 => '0039-37-01-G',
                    14 => '0039-37-01-H',
                ),
            ),
        );
    }

    /**
    * test the set routine when an extra class exists
    *
    * @param string $name   The name of the variable to test.
    * @param array  $expect The expected return
    *
    * @return null 
    *
    * @dataProvider dataGetEndpoints
    */
    public function testGetEndpoints($name, $expect)
    {
        $this->assertSame($expect, $this->o->getEndpoints($name));
    }

    /**
    * data provider for testGetDaughterboards
    *
    * @return array
    */
    public static function dataGetDaughterboards()
    {
        return array(
            array(
                true,
                array(
                    0 => '0039-15-01',
                    1 => '0039-16-01',
                    2 => '0039-23-01',
                ),
            ),
        );
    }

    /**
    *************************************************************
    * test routine for get daughterboards list
    *
    * @param string $name   The name of the variable to test
    * @param array  $expect The expected return.
    *
    * @return null
    *
    * @dataProvider dataGetDaughterboards
    */
    public function testGetDaughterboards($name, $expect)
    {
        $this->assertSame($expect, $this->o->getDaughterboards($name));
    }

    /**
    * data provider for testEpPinList
    *
    * @return array
    */
    public static function dataEpPinList()
    {
        return array(
            array(
                "0039-12-02-C",
                array(
                    0 => 'Port1',
                    1 => 'Port2',
                    2 => 'Port3',
                    3 => 'Port4',
                    4 => 'Port5',
                    5 => 'Port6',
                    6 => 'Port7',
                    7 => 'Port8',
                    8 => 'Port9',
                    9 => 'Port10',
                    10 => 'Port11',
                    11 => 'Port12',
                ),
            ),
            array(
                "0039-12-04-A",
                array(
                   0 => 'Error',
                   1 => 'Endpoint not found!',
                ),
            ),
            array(
                "0039-12-01-A",
                array(
                   0 => 'Error',
                   1 => 'No Pins to display!',
                ),
            ),
        );
    }




    /**
    *************************************************************
    * test routine for get endpoint pins list
    *
    * @param string $name   The name of the variable to test
    * @param array  $expect The expected return.
    *
    * @return null
    *
    * @dataProvider dataEpPinList
    */
    public function testEpPinList($name, $expect)
    {
        $this->assertSame($expect, $this->o->epPinList($name));
    }

    /**
    * data provider for testEpPinProperties
    *
    * @return array
    */
    public static function dataEpPinProperties()
    {
        return array(
            array(
                "0039-37-01-C",
                "Port2",
                array(
                    0 => 'AI',
                    1 => '1K',
                    2 => '10K',
                    3 => 'R18',
                    4 => 'CGND',
                ),
            ),
            array(
                "0039-37-02-C",
                "Port2",
                array(
                    0 => 'Error',
                    1 => 'Endpoint not found!',
                ),
            ),
            array(
                "0039-37-01-C",
                "Port9",
                array(
                    0 => 'Error',
                    1 => 'Pin not found!',
                ),
            ),
            array(
                "0039-12-01-A",
                "Port2",
                array(
                    0 => 'Error',
                    1 => 'No Pins to display!',
                ),
            ),
        );
    }


    /**
    *************************************************************
    * test routine for get endpoint pin properties
    *
    * @param string $name   The name of the variable to test
    * @param string $pin    The name of the pin to test
    * @param array  $expect The expected return.
    *
    * @return null
    *
    * @dataProvider dataEpPinProperties
    */
    public function testEpPinProperties($name, $pin, $expect)
    {
        $this->assertSame($expect, $this->o->epPinProperties($name, $pin));
    }


    /**
    * data provider for testDbPinList
    *
    * @return array
    */
    public static function dataDbPinList()
    {
        return array(
            array(
                "0039-23-01",
                array(
                    0 => 'Port1',
                    1 => 'Port2',
                    2 => 'Port3',
                    3 => 'Port4',
                    4 => 'Port5',
                    5 => 'Port6',
                    6 => 'Port7',
                    7 => 'Port8',
                    8 => 'Port9',
                    9 => 'Port10',
                    10 => 'Port11',
                    11 => 'Port12',
                    12 => 'Port13',
                    13 => 'Port14',
                    14 => 'Port15',
                    15 => 'Port16',
                ),
            ),
            array(
                "0039-17-01",
                array(
                   0 => 'Error',
                   1 => 'Daughterboard not found!',
                ),
            ),
        );
    }


    /**
    *************************************************************
    * test routine for get daughterboard pins list
    *
    * @param string $name   The name of the variable to test
    * @param array  $expect The expected return.
    *
    * @return null
    *
    * @dataProvider dataDbPinList
    */
    public function testDbPinList($name, $expect)
    {
        $this->assertSame($expect, $this->o->dbPinList($name));
    }

    /**
    * data provider for testDbPinProperties
    *
    * @return array
    */
    public static function dataDbPinProperties()
    {
        return array(
            array(
                "0039-15-01",
                "Port2",
                array(
                    0 => array(
                            0 => 'AI',
                        ),
                    1 => array(
                            0 => 'Connect',
                            1 => '0039-12-02-C',
                            2 => 'Port2',
                         ),
                    2 => array(
                            0 => 'Connect',
                            1 => '0039-28-01-A',
                            2 => 'Port2',
                        ),
                ),
            ),
            array(
                "0039-22-01",
                "Port2",
                array(
                    0 => array(
                            0 => 'Error',
                            1 => 'Daughterboard not found!',
                        ),
                ),
            ),
            array(
                "0039-15-01",
                "Port10",
                array(
                    0 => array(
                            0 => 'Error',
                            1 => 'Pin not found!',
                        ),
                ),
            ),
        );
    }


    /**
    *************************************************************
    * test routine for get daughterboard pin properties
    *
    * @param string $name   The name of the variable to test
    * @param string $pin    The name of the pin to test
    * @param array  $expect The expected return.
    *
    * @return null
    *
    * @dataProvider dataDbPinProperties
    */
    public function testDbPinProperties($name, $pin, $expect)
    {
        $this->assertSame($expect, $this->o->dbPinProperties($name, $pin));
    }

    /**
    * data provider for testDbToEpConnections
    *
    * @return array
    */
    public static function dataDbToEpConnections()
    {
        return array(
            array(
                "0039-23-01",
                "0039-28-01-A",
                array(
                    0 => array(
                            0 => 'Port1',
                            1 => 'PC0',
                        ),
                    1 => array(
                            0 => 'Port2',
                            1 => 'PC1',
                        ),
                    2 => array(
                            0 => 'Port3',
                            1 => 'PC2',
                        ),
                    3 => array(
                            0 => 'Port4',
                            1 => 'PC3',
                        ),
                    4 => array(
                            0 => 'Port5',
                            1 => 'PC4',
                        ),
                    5 => array(
                            0 => 'Port6',
                            1 => 'PC5'
                        ),
                    6 => array( 
                            0 => 'Port7',
                            1 => 'ADC6',
                        ),
                    7 => array(
                            0 => 'Port8',
                            1 => 'ADC7'
                        ),
                    8 => array(
                            0 => 'Port9',
                            1 => 'PB0',
                        ),
                    9 => array(
                            0 => 'Port10',
                            1 => 'PB1',
                        ),
                    10 => array(
                            0 => 'Port11',
                            1 => 'PB2',
                        ),
                    11 => array(
                            0 => 'Port12',
                            1 => 'PB3',
                        ),
                    12 => array(
                            0 => 'Port13',
                            1 => 'PB4',
                        ),
                    13 => array(
                            0 => 'Port14',
                            1 => 'PB5',
                        ),
                    14 => array(
                            0 => 'Port15',
                            1 => 'PD5',
                        ),
                    15 => array(
                            0 => 'Port16',
                            1 => 'PD6',
                        ),
                ),
            ),
            array(
                "0039-24-01",
                "0039-28-01-A",
                array(
                    0 => array(
                            0 => 'Error',
                            1 => 'Daughterboard not found!',
                        ),
                ),
            ),
            array(
                "0039-23-01",
                "0039-17-01-A",
                array(
                    0 => array(
                            0 => 'Error',
                            1 => 'Endpoint not found in connections',
                        ),
                    1 => array(
                            0 => 'Port2',
                        ),
                    2 => array(
                            0 => 'Port3',
                        ),
                    3 => array(
                            0 => 'Port4',
                        ),
                    4 => array(
                            0 => 'Port5',
                        ),
                    5 => array(
                            0 => 'Port6',
                        ),
                    6 => array( 
                            0 => 'Port7',
                        ),
                    7 => array(
                            0 => 'Port8',
                        ),
                    8 => array(
                            0 => 'Port9',
                        ),
                    9 => array(
                            0 => 'Port10',
                        ),
                    10 => array(
                            0 => 'Port11',
                        ),
                    11 => array(
                            0 => 'Port12',
                        ),
                    12 => array(
                            0 => 'Port13',
                        ),
                    13 => array(
                            0 => 'Port14',
                        ),
                    14 => array(
                            0 => 'Port15',
                        ),
                    15 => array(
                            0 => 'Port16',
                        ),
                ),
            ),
        );
    }

    /**
    *************************************************************
    * test routine for get daughterboard to endpoint connections
    *
    * @param string $dbname   The name of the daughterboard test
    * @param string $epname  The name of the endpoint test
    * @param array  $expect The expected return.
    *
    * @return null
    *
    * @dataProvider dataDbToEpConnections
    */
    public function testDbToEpPConnections($dbname, $epname, $expect)
    {
        $this->assertSame($expect, $this->o->dbToEpConnections($dbname, $epname));
    }


    /**
    *************************************************************
    * test routine for constructor using default filename
    *
    * @param string $name - name of the variable to test
    * @param array  $expect - the expected return
    *
    * @return null
    *
    * @dataProvider dataGetDaughterboards
    */
    public function testConstructor($name, $expect)
    {
       
        unset($this->o);
        $this->o = Properties::factory();   
        $this->assertSame($expect, $this->o->getDaughterboards($name));
    }


}
?>
