<?php
/**
 * This runs all of the tests associated with HUGnetLib.
 *
 * PHP Version 5
 *
 * <pre>
 * HUGnetLib is a library of HUGnet code
 * Copyright (C) 2013 Hunt Utilities Group, LLC
 * Copyright (C) 2009 Scott Price
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 * </pre>
 *
 * @category   Libraries
 * @package    HUGnetLibTest
 * @subpackage SuiteBase
 * @author     Scott Price <prices@hugllc.com>
 * @copyright  2013 Hunt Utilities Group, LLC
 * @copyright  2009 Scott Price
 * @license    http://opensource.org/licenses/gpl-license.php GNU Public License
 * @link       http://dev.hugllc.com/index.php/Project:HUGnetLib
 */
/** This is the HUGnet namespace */
namespace HUGnet\devices;
/** This is a required class */
require_once CODE_BASE.'devices/Role.php';
/** This is a required class */
require_once CODE_BASE.'system/System.php';

/**
 * Test class for HUGnetDB.
 * Generated by PHPUnit on 2007-12-13 at 10:28:11.
 *
 * @category   Libraries
 * @package    HUGnetLibTest
 * @subpackage SuiteBase
 * @author     Scott Price <prices@hugllc.com>
 * @copyright  2013 Hunt Utilities Group, LLC
 * @copyright  2009 Scott Price
 * @license    http://opensource.org/licenses/gpl-license.php GNU Public License
 * @version    Release: 0.10.2
 * @link       http://dev.hugllc.com/index.php/Project:HUGnetLib
 */
class RoleTest extends \PHPUnit_Framework_TestCase
{
    /**
    * Sets up the fixture, for example, opens a network connection.
    * This method is called before a test is executed.
    *
    * @access protected
    *
    * @return null
    */
    protected function setUp()
    {
        $this->o = Role::factory();
    }

    /**
    * Tears down the fixture, for example, closes a network connection.
    * This method is called after a test is executed.
    *
    * @access protected
    *
    * @return null
    */
    protected function tearDown()
    {
        unset($this->o);
    }

    /**
    * data provider for testDeviceID
    *
    * @return array
    */
    public static function dataInput()
    {
        return array(
            array(
                "BadName", 0, null
            ),
            array(
                "Controller",
                0,
                array(
                    "table" => array(
                        'driver' => '40:DEFAULT',
                        'name' => 'Controller Board Voltage',
                        'MUX' => 4,
                        'id' => 0,
                        'ADLAR' => 1,
                        'REFS' => 1,
                    ),
                    "data" => array(
                        "extra" => array(180, 27, 5.0),
                        "location" => "HUGnet 1 Voltage High",
                        "type" => "AVRAnalogTable",
                        "id" => 0xF8,
                    ),
                ),
            ),
        );
    }
    /**
    * test the set routine when an extra class exists
    *
    * @param string $name   The name role.
    * @param int    $sid    The ID value to look for
    * @param array  $expect The expected return
    *
    * @return null
    *
    * @dataProvider dataInput
    */
    public function testInput($name, $sid, $expect)
    {
        $ret = $this->o->input($name, $sid);
        $this->assertEquals($expect, $ret);
    }
    /**
    * data provider for testProcess
    *
    * @return array
    */
    public static function dataProcess()
    {
        return array(
            array(
                "BadName", 0, null
            ),
            array(
                "Controller", 0, null
            ),
        );
    }
    /**
    * test the set routine when an extra class exists
    *
    * @param string $name   The name role.
    * @param int    $sid    The ID value to look for
    * @param array  $expect The expected return
    *
    * @return null
    *
    * @dataProvider dataProcess
    */
    public function testProcess($name, $sid, $expect)
    {
        $ret = $this->o->process($name, $sid);
        $this->assertEquals($expect, $ret);
    }
    /**
    * data provider for testDeviceID
    *
    * @return array
    */
    public static function dataOutput()
    {
        return array(
            array(
                "BadName", 0, null
            ),
            array(
                "Controller",
                0,
                array(
                    "table" => array(),
                    "data" => array(
                        "extra" => array(0, 1),
                        "location" => "HUGnet 0 Power",
                        "id" => 0x30,
                        "type" => "HUGnetPower",
                    ),
                ),
            ),
        );
    }
    /**
    * test the set routine when an extra class exists
    *
    * @param string $name   The name role.
    * @param int    $sid    The ID value to look for
    * @param array  $expect The expected return
    *
    * @return null
    *
    * @dataProvider dataOutput
    */
    public function testOutput($name, $sid, $expect)
    {
        $ret = $this->o->output($name, $sid);
        $this->assertEquals($expect, $ret);
    }
    /**
    * data provider for testGetAll
    *
    * @return array
    */
    public static function dataGetAll()
    {
        return array(
            array(
                "BadName", null
            ),
            array(
                "Linux", array()
            ),
        );
    }
    /**
    * test the set routine when an extra class exists
    *
    * @param string $arch   The name of the arch
    * @param array  $expect The expected return
    *
    * @return null
    *
    * @dataProvider dataGetAll
    */
    public function testGetAll($arch, $expect)
    {
        $ret = $this->o->getAll($arch);
        $this->assertSame($expect, $ret);
    }
}
?>
